package fis.repository.fs.dao;

import fis.repository.fs.model.FsBaseBillinfo;
import fis.repository.fs.model.FsBaseBillinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface FsBaseBillinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_BASE_BILLINFO
     *
     * @mbggenerated Wed Dec 21 10:11:04 CST 2011
     */
    int countByExample(FsBaseBillinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_BASE_BILLINFO
     *
     * @mbggenerated Wed Dec 21 10:11:04 CST 2011
     */
    int deleteByExample(FsBaseBillinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_BASE_BILLINFO
     *
     * @mbggenerated Wed Dec 21 10:11:04 CST 2011
     */
    int insert(FsBaseBillinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_BASE_BILLINFO
     *
     * @mbggenerated Wed Dec 21 10:11:04 CST 2011
     */
    int insertSelective(FsBaseBillinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_BASE_BILLINFO
     *
     * @mbggenerated Wed Dec 21 10:11:04 CST 2011
     */
    List<FsBaseBillinfo> selectByExample(FsBaseBillinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_BASE_BILLINFO
     *
     * @mbggenerated Wed Dec 21 10:11:04 CST 2011
     */
    int updateByExampleSelective(@Param("record") FsBaseBillinfo record, @Param("example") FsBaseBillinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_BASE_BILLINFO
     *
     * @mbggenerated Wed Dec 21 10:11:04 CST 2011
     */
    int updateByExample(@Param("record") FsBaseBillinfo record, @Param("example") FsBaseBillinfoExample example);
}