package fis.repository.fs.dao;

import fis.repository.fs.model.FsBasePrograminfo;
import fis.repository.fs.model.FsBasePrograminfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface FsBasePrograminfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_BASE_PROGRAMINFO
     *
     * @mbggenerated Thu Dec 22 09:19:45 CST 2011
     */
    int countByExample(FsBasePrograminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_BASE_PROGRAMINFO
     *
     * @mbggenerated Thu Dec 22 09:19:45 CST 2011
     */
    int deleteByExample(FsBasePrograminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_BASE_PROGRAMINFO
     *
     * @mbggenerated Thu Dec 22 09:19:45 CST 2011
     */
    int insert(FsBasePrograminfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_BASE_PROGRAMINFO
     *
     * @mbggenerated Thu Dec 22 09:19:45 CST 2011
     */
    int insertSelective(FsBasePrograminfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_BASE_PROGRAMINFO
     *
     * @mbggenerated Thu Dec 22 09:19:45 CST 2011
     */
    List<FsBasePrograminfo> selectByExample(FsBasePrograminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_BASE_PROGRAMINFO
     *
     * @mbggenerated Thu Dec 22 09:19:45 CST 2011
     */
    int updateByExampleSelective(@Param("record") FsBasePrograminfo record, @Param("example") FsBasePrograminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_BASE_PROGRAMINFO
     *
     * @mbggenerated Thu Dec 22 09:19:45 CST 2011
     */
    int updateByExample(@Param("record") FsBasePrograminfo record, @Param("example") FsBasePrograminfoExample example);
}