package fis.repository.fs.dao;

import fis.repository.fs.model.FsPaymentinfo;
import fis.repository.fs.model.FsPaymentinfoExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface FsPaymentinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_PAYMENTINFO
     *
     * @mbggenerated Sat Jan 07 17:41:26 CST 2012
     */
    int countByExample(FsPaymentinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_PAYMENTINFO
     *
     * @mbggenerated Sat Jan 07 17:41:26 CST 2012
     */
    int deleteByExample(FsPaymentinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_PAYMENTINFO
     *
     * @mbggenerated Sat Jan 07 17:41:26 CST 2012
     */
    int insert(FsPaymentinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_PAYMENTINFO
     *
     * @mbggenerated Sat Jan 07 17:41:26 CST 2012
     */
    int insertSelective(FsPaymentinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_PAYMENTINFO
     *
     * @mbggenerated Sat Jan 07 17:41:26 CST 2012
     */
    List<FsPaymentinfo> selectByExample(FsPaymentinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_PAYMENTINFO
     *
     * @mbggenerated Sat Jan 07 17:41:26 CST 2012
     */
    int updateByExampleSelective(@Param("record") FsPaymentinfo record, @Param("example") FsPaymentinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_PAYMENTINFO
     *
     * @mbggenerated Sat Jan 07 17:41:26 CST 2012
     */
    int updateByExample(@Param("record") FsPaymentinfo record, @Param("example") FsPaymentinfoExample example);

    List<FsPaymentinfo> selectPayinfoByPaynotescd(@Param("paynotescd") String paynotescd, @Param("checkcode") String checkcode,
                                                  @Param("bofcode") String bofcode);

    List<FsPaymentinfo> selectPayinfoForToact(Map m);

    List<FsPaymentinfo> selectPayinfoForQry(@Param("processstatus") String processstatus,@Param("bofcode") String bofcode,
                                            @Param("notescode") String notescode,@Param("recStartd") String recStartd,
                                            @Param("recEndd") String recEndd,@Param("acctStartd") String acctStratd,
                                            @Param("acctEndd") String acctEndd );

}