package fis.repository.fs.dao;

import fis.repository.fs.model.FsRefundinfo;
import fis.repository.fs.model.FsRefundinfoExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface FsRefundinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_REFUNDINFO
     *
     * @mbggenerated Sat Jan 07 17:48:51 CST 2012
     */
    int countByExample(FsRefundinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_REFUNDINFO
     *
     * @mbggenerated Sat Jan 07 17:48:51 CST 2012
     */
    int deleteByExample(FsRefundinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_REFUNDINFO
     *
     * @mbggenerated Sat Jan 07 17:48:51 CST 2012
     */
    int insert(FsRefundinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_REFUNDINFO
     *
     * @mbggenerated Sat Jan 07 17:48:51 CST 2012
     */
    int insertSelective(FsRefundinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_REFUNDINFO
     *
     * @mbggenerated Sat Jan 07 17:48:51 CST 2012
     */
    List<FsRefundinfo> selectByExample(FsRefundinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_REFUNDINFO
     *
     * @mbggenerated Sat Jan 07 17:48:51 CST 2012
     */
    int updateByExampleSelective(@Param("record") FsRefundinfo record, @Param("example") FsRefundinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_REFUNDINFO
     *
     * @mbggenerated Sat Jan 07 17:48:51 CST 2012
     */
    int updateByExample(@Param("record") FsRefundinfo record, @Param("example") FsRefundinfoExample example);

    /**
     * haiyuhuang
     * ∞¥ÕÀ∏∂…Í«Î∫≈≤È—Ø*/
    List<FsRefundinfo> selectByRefundAppCode(@Param("refundappcode") String refundappcode, @Param("bofcode") String bofcode);
}