package fis.repository.gwk.dao;

import fis.repository.gwk.model.GwkAreacodeMap;
import fis.repository.gwk.model.GwkAreacodeMapExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface GwkAreacodeMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.GWK_AREACODE_MAP
     *
     * @mbggenerated Mon Dec 17 21:55:18 CST 2012
     */
    int countByExample(GwkAreacodeMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.GWK_AREACODE_MAP
     *
     * @mbggenerated Mon Dec 17 21:55:18 CST 2012
     */
    int deleteByExample(GwkAreacodeMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.GWK_AREACODE_MAP
     *
     * @mbggenerated Mon Dec 17 21:55:18 CST 2012
     */
    int insert(GwkAreacodeMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.GWK_AREACODE_MAP
     *
     * @mbggenerated Mon Dec 17 21:55:18 CST 2012
     */
    int insertSelective(GwkAreacodeMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.GWK_AREACODE_MAP
     *
     * @mbggenerated Mon Dec 17 21:55:18 CST 2012
     */
    List<GwkAreacodeMap> selectByExample(GwkAreacodeMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.GWK_AREACODE_MAP
     *
     * @mbggenerated Mon Dec 17 21:55:18 CST 2012
     */
    int updateByExampleSelective(@Param("record") GwkAreacodeMap record, @Param("example") GwkAreacodeMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.GWK_AREACODE_MAP
     *
     * @mbggenerated Mon Dec 17 21:55:18 CST 2012
     */
    int updateByExample(@Param("record") GwkAreacodeMap record, @Param("example") GwkAreacodeMapExample example);
}