package fis.repository.gwk.dao;

import fis.repository.gwk.model.GwkConsumeinfo;
import fis.repository.gwk.model.GwkConsumeinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface GwkConsumeinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.GWK_CONSUMEINFO
     *
     * @mbggenerated Sat Jan 07 23:10:01 CST 2012
     */
    int countByExample(GwkConsumeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.GWK_CONSUMEINFO
     *
     * @mbggenerated Sat Jan 07 23:10:01 CST 2012
     */
    int deleteByExample(GwkConsumeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.GWK_CONSUMEINFO
     *
     * @mbggenerated Sat Jan 07 23:10:01 CST 2012
     */
    int insert(GwkConsumeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.GWK_CONSUMEINFO
     *
     * @mbggenerated Sat Jan 07 23:10:01 CST 2012
     */
    int insertSelective(GwkConsumeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.GWK_CONSUMEINFO
     *
     * @mbggenerated Sat Jan 07 23:10:01 CST 2012
     */
    List<GwkConsumeinfo> selectByExample(GwkConsumeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.GWK_CONSUMEINFO
     *
     * @mbggenerated Sat Jan 07 23:10:01 CST 2012
     */
    int updateByExampleSelective(@Param("record") GwkConsumeinfo record, @Param("example") GwkConsumeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.GWK_CONSUMEINFO
     *
     * @mbggenerated Sat Jan 07 23:10:01 CST 2012
     */
    int updateByExample(@Param("record") GwkConsumeinfo record, @Param("example") GwkConsumeinfoExample example);
}