package fis.repository.gwk.dao;

import fis.repository.gwk.model.GwkPaybackinfo;
import fis.repository.gwk.model.GwkPaybackinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface GwkPaybackinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.GWK_PAYBACKINFO
     *
     * @mbggenerated Sun Jan 08 10:52:09 CST 2012
     */
    int countByExample(GwkPaybackinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.GWK_PAYBACKINFO
     *
     * @mbggenerated Sun Jan 08 10:52:09 CST 2012
     */
    int deleteByExample(GwkPaybackinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.GWK_PAYBACKINFO
     *
     * @mbggenerated Sun Jan 08 10:52:09 CST 2012
     */
    int insert(GwkPaybackinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.GWK_PAYBACKINFO
     *
     * @mbggenerated Sun Jan 08 10:52:09 CST 2012
     */
    int insertSelective(GwkPaybackinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.GWK_PAYBACKINFO
     *
     * @mbggenerated Sun Jan 08 10:52:09 CST 2012
     */
    List<GwkPaybackinfo> selectByExample(GwkPaybackinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.GWK_PAYBACKINFO
     *
     * @mbggenerated Sun Jan 08 10:52:09 CST 2012
     */
    int updateByExampleSelective(@Param("record") GwkPaybackinfo record, @Param("example") GwkPaybackinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.GWK_PAYBACKINFO
     *
     * @mbggenerated Sun Jan 08 10:52:09 CST 2012
     */
    int updateByExample(@Param("record") GwkPaybackinfo record, @Param("example") GwkPaybackinfoExample example);

    /*create by haiyuhuang 20120108*/
    List<GwkPaybackinfo> selectPaybackinfo4File();
}