package fis.repository.model;

import java.util.Date;

public class FsBaseIteminfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_BASE_ITEMINFO.PKID
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_BASE_ITEMINFO.ITEMCODE
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    private String itemcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_BASE_ITEMINFO.ITEMNAME
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    private String itemname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_BASE_ITEMINFO.ITEMID
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    private String itemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_BASE_ITEMINFO.VERSION
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_BASE_ITEMINFO.OPERID
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    private String operid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_BASE_ITEMINFO.OPERDATE
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    private Date operdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_BASE_ITEMINFO.PKID
     *
     * @return the value of FIS.FS_BASE_ITEMINFO.PKID
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_BASE_ITEMINFO.PKID
     *
     * @param pkid the value for FIS.FS_BASE_ITEMINFO.PKID
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_BASE_ITEMINFO.ITEMCODE
     *
     * @return the value of FIS.FS_BASE_ITEMINFO.ITEMCODE
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public String getItemcode() {
        return itemcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_BASE_ITEMINFO.ITEMCODE
     *
     * @param itemcode the value for FIS.FS_BASE_ITEMINFO.ITEMCODE
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public void setItemcode(String itemcode) {
        this.itemcode = itemcode == null ? null : itemcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_BASE_ITEMINFO.ITEMNAME
     *
     * @return the value of FIS.FS_BASE_ITEMINFO.ITEMNAME
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public String getItemname() {
        return itemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_BASE_ITEMINFO.ITEMNAME
     *
     * @param itemname the value for FIS.FS_BASE_ITEMINFO.ITEMNAME
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public void setItemname(String itemname) {
        this.itemname = itemname == null ? null : itemname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_BASE_ITEMINFO.ITEMID
     *
     * @return the value of FIS.FS_BASE_ITEMINFO.ITEMID
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public String getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_BASE_ITEMINFO.ITEMID
     *
     * @param itemid the value for FIS.FS_BASE_ITEMINFO.ITEMID
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public void setItemid(String itemid) {
        this.itemid = itemid == null ? null : itemid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_BASE_ITEMINFO.VERSION
     *
     * @return the value of FIS.FS_BASE_ITEMINFO.VERSION
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_BASE_ITEMINFO.VERSION
     *
     * @param version the value for FIS.FS_BASE_ITEMINFO.VERSION
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_BASE_ITEMINFO.OPERID
     *
     * @return the value of FIS.FS_BASE_ITEMINFO.OPERID
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public String getOperid() {
        return operid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_BASE_ITEMINFO.OPERID
     *
     * @param operid the value for FIS.FS_BASE_ITEMINFO.OPERID
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public void setOperid(String operid) {
        this.operid = operid == null ? null : operid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_BASE_ITEMINFO.OPERDATE
     *
     * @return the value of FIS.FS_BASE_ITEMINFO.OPERDATE
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public Date getOperdate() {
        return operdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_BASE_ITEMINFO.OPERDATE
     *
     * @param operdate the value for FIS.FS_BASE_ITEMINFO.OPERDATE
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public void setOperdate(Date operdate) {
        this.operdate = operdate;
    }
}