package fis.repository.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FsBaseBaseinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_BASE_BASEINFO
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_BASE_BASEINFO
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_BASE_BASEINFO
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_BASE_BASEINFO
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public FsBaseBaseinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_BASE_BASEINFO
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_BASE_BASEINFO
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_BASE_BASEINFO
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_BASE_BASEINFO
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_BASE_BASEINFO
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_BASE_BASEINFO
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_BASE_BASEINFO
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_BASE_BASEINFO
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_BASE_BASEINFO
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_BASE_BASEINFO
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_BASE_BASEINFO
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andBankIsNull() {
            addCriterion("BANK is null");
            return (Criteria) this;
        }

        public Criteria andBankIsNotNull() {
            addCriterion("BANK is not null");
            return (Criteria) this;
        }

        public Criteria andBankEqualTo(String value) {
            addCriterion("BANK =", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankNotEqualTo(String value) {
            addCriterion("BANK <>", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankGreaterThan(String value) {
            addCriterion("BANK >", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankGreaterThanOrEqualTo(String value) {
            addCriterion("BANK >=", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankLessThan(String value) {
            addCriterion("BANK <", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankLessThanOrEqualTo(String value) {
            addCriterion("BANK <=", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankLike(String value) {
            addCriterion("BANK like", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankNotLike(String value) {
            addCriterion("BANK not like", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankIn(List<String> values) {
            addCriterion("BANK in", values, "bank");
            return (Criteria) this;
        }

        public Criteria andBankNotIn(List<String> values) {
            addCriterion("BANK not in", values, "bank");
            return (Criteria) this;
        }

        public Criteria andBankBetween(String value1, String value2) {
            addCriterion("BANK between", value1, value2, "bank");
            return (Criteria) this;
        }

        public Criteria andBankNotBetween(String value1, String value2) {
            addCriterion("BANK not between", value1, value2, "bank");
            return (Criteria) this;
        }

        public Criteria andFsagencyIsNull() {
            addCriterion("FSAGENCY is null");
            return (Criteria) this;
        }

        public Criteria andFsagencyIsNotNull() {
            addCriterion("FSAGENCY is not null");
            return (Criteria) this;
        }

        public Criteria andFsagencyEqualTo(String value) {
            addCriterion("FSAGENCY =", value, "fsagency");
            return (Criteria) this;
        }

        public Criteria andFsagencyNotEqualTo(String value) {
            addCriterion("FSAGENCY <>", value, "fsagency");
            return (Criteria) this;
        }

        public Criteria andFsagencyGreaterThan(String value) {
            addCriterion("FSAGENCY >", value, "fsagency");
            return (Criteria) this;
        }

        public Criteria andFsagencyGreaterThanOrEqualTo(String value) {
            addCriterion("FSAGENCY >=", value, "fsagency");
            return (Criteria) this;
        }

        public Criteria andFsagencyLessThan(String value) {
            addCriterion("FSAGENCY <", value, "fsagency");
            return (Criteria) this;
        }

        public Criteria andFsagencyLessThanOrEqualTo(String value) {
            addCriterion("FSAGENCY <=", value, "fsagency");
            return (Criteria) this;
        }

        public Criteria andFsagencyLike(String value) {
            addCriterion("FSAGENCY like", value, "fsagency");
            return (Criteria) this;
        }

        public Criteria andFsagencyNotLike(String value) {
            addCriterion("FSAGENCY not like", value, "fsagency");
            return (Criteria) this;
        }

        public Criteria andFsagencyIn(List<String> values) {
            addCriterion("FSAGENCY in", values, "fsagency");
            return (Criteria) this;
        }

        public Criteria andFsagencyNotIn(List<String> values) {
            addCriterion("FSAGENCY not in", values, "fsagency");
            return (Criteria) this;
        }

        public Criteria andFsagencyBetween(String value1, String value2) {
            addCriterion("FSAGENCY between", value1, value2, "fsagency");
            return (Criteria) this;
        }

        public Criteria andFsagencyNotBetween(String value1, String value2) {
            addCriterion("FSAGENCY not between", value1, value2, "fsagency");
            return (Criteria) this;
        }

        public Criteria andStrorageidIsNull() {
            addCriterion("STRORAGEID is null");
            return (Criteria) this;
        }

        public Criteria andStrorageidIsNotNull() {
            addCriterion("STRORAGEID is not null");
            return (Criteria) this;
        }

        public Criteria andStrorageidEqualTo(String value) {
            addCriterion("STRORAGEID =", value, "strorageid");
            return (Criteria) this;
        }

        public Criteria andStrorageidNotEqualTo(String value) {
            addCriterion("STRORAGEID <>", value, "strorageid");
            return (Criteria) this;
        }

        public Criteria andStrorageidGreaterThan(String value) {
            addCriterion("STRORAGEID >", value, "strorageid");
            return (Criteria) this;
        }

        public Criteria andStrorageidGreaterThanOrEqualTo(String value) {
            addCriterion("STRORAGEID >=", value, "strorageid");
            return (Criteria) this;
        }

        public Criteria andStrorageidLessThan(String value) {
            addCriterion("STRORAGEID <", value, "strorageid");
            return (Criteria) this;
        }

        public Criteria andStrorageidLessThanOrEqualTo(String value) {
            addCriterion("STRORAGEID <=", value, "strorageid");
            return (Criteria) this;
        }

        public Criteria andStrorageidLike(String value) {
            addCriterion("STRORAGEID like", value, "strorageid");
            return (Criteria) this;
        }

        public Criteria andStrorageidNotLike(String value) {
            addCriterion("STRORAGEID not like", value, "strorageid");
            return (Criteria) this;
        }

        public Criteria andStrorageidIn(List<String> values) {
            addCriterion("STRORAGEID in", values, "strorageid");
            return (Criteria) this;
        }

        public Criteria andStrorageidNotIn(List<String> values) {
            addCriterion("STRORAGEID not in", values, "strorageid");
            return (Criteria) this;
        }

        public Criteria andStrorageidBetween(String value1, String value2) {
            addCriterion("STRORAGEID between", value1, value2, "strorageid");
            return (Criteria) this;
        }

        public Criteria andStrorageidNotBetween(String value1, String value2) {
            addCriterion("STRORAGEID not between", value1, value2, "strorageid");
            return (Criteria) this;
        }

        public Criteria andProgramIsNull() {
            addCriterion("PROGRAM is null");
            return (Criteria) this;
        }

        public Criteria andProgramIsNotNull() {
            addCriterion("PROGRAM is not null");
            return (Criteria) this;
        }

        public Criteria andProgramEqualTo(String value) {
            addCriterion("PROGRAM =", value, "program");
            return (Criteria) this;
        }

        public Criteria andProgramNotEqualTo(String value) {
            addCriterion("PROGRAM <>", value, "program");
            return (Criteria) this;
        }

        public Criteria andProgramGreaterThan(String value) {
            addCriterion("PROGRAM >", value, "program");
            return (Criteria) this;
        }

        public Criteria andProgramGreaterThanOrEqualTo(String value) {
            addCriterion("PROGRAM >=", value, "program");
            return (Criteria) this;
        }

        public Criteria andProgramLessThan(String value) {
            addCriterion("PROGRAM <", value, "program");
            return (Criteria) this;
        }

        public Criteria andProgramLessThanOrEqualTo(String value) {
            addCriterion("PROGRAM <=", value, "program");
            return (Criteria) this;
        }

        public Criteria andProgramLike(String value) {
            addCriterion("PROGRAM like", value, "program");
            return (Criteria) this;
        }

        public Criteria andProgramNotLike(String value) {
            addCriterion("PROGRAM not like", value, "program");
            return (Criteria) this;
        }

        public Criteria andProgramIn(List<String> values) {
            addCriterion("PROGRAM in", values, "program");
            return (Criteria) this;
        }

        public Criteria andProgramNotIn(List<String> values) {
            addCriterion("PROGRAM not in", values, "program");
            return (Criteria) this;
        }

        public Criteria andProgramBetween(String value1, String value2) {
            addCriterion("PROGRAM between", value1, value2, "program");
            return (Criteria) this;
        }

        public Criteria andProgramNotBetween(String value1, String value2) {
            addCriterion("PROGRAM not between", value1, value2, "program");
            return (Criteria) this;
        }

        public Criteria andMkuserIsNull() {
            addCriterion("MKUSER is null");
            return (Criteria) this;
        }

        public Criteria andMkuserIsNotNull() {
            addCriterion("MKUSER is not null");
            return (Criteria) this;
        }

        public Criteria andMkuserEqualTo(String value) {
            addCriterion("MKUSER =", value, "mkuser");
            return (Criteria) this;
        }

        public Criteria andMkuserNotEqualTo(String value) {
            addCriterion("MKUSER <>", value, "mkuser");
            return (Criteria) this;
        }

        public Criteria andMkuserGreaterThan(String value) {
            addCriterion("MKUSER >", value, "mkuser");
            return (Criteria) this;
        }

        public Criteria andMkuserGreaterThanOrEqualTo(String value) {
            addCriterion("MKUSER >=", value, "mkuser");
            return (Criteria) this;
        }

        public Criteria andMkuserLessThan(String value) {
            addCriterion("MKUSER <", value, "mkuser");
            return (Criteria) this;
        }

        public Criteria andMkuserLessThanOrEqualTo(String value) {
            addCriterion("MKUSER <=", value, "mkuser");
            return (Criteria) this;
        }

        public Criteria andMkuserLike(String value) {
            addCriterion("MKUSER like", value, "mkuser");
            return (Criteria) this;
        }

        public Criteria andMkuserNotLike(String value) {
            addCriterion("MKUSER not like", value, "mkuser");
            return (Criteria) this;
        }

        public Criteria andMkuserIn(List<String> values) {
            addCriterion("MKUSER in", values, "mkuser");
            return (Criteria) this;
        }

        public Criteria andMkuserNotIn(List<String> values) {
            addCriterion("MKUSER not in", values, "mkuser");
            return (Criteria) this;
        }

        public Criteria andMkuserBetween(String value1, String value2) {
            addCriterion("MKUSER between", value1, value2, "mkuser");
            return (Criteria) this;
        }

        public Criteria andMkuserNotBetween(String value1, String value2) {
            addCriterion("MKUSER not between", value1, value2, "mkuser");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("VERSION is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("VERSION =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("VERSION <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("VERSION >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("VERSION >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("VERSION <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("VERSION <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("VERSION in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("VERSION not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("VERSION between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("VERSION not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andOperidIsNull() {
            addCriterion("OPERID is null");
            return (Criteria) this;
        }

        public Criteria andOperidIsNotNull() {
            addCriterion("OPERID is not null");
            return (Criteria) this;
        }

        public Criteria andOperidEqualTo(String value) {
            addCriterion("OPERID =", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotEqualTo(String value) {
            addCriterion("OPERID <>", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidGreaterThan(String value) {
            addCriterion("OPERID >", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidGreaterThanOrEqualTo(String value) {
            addCriterion("OPERID >=", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidLessThan(String value) {
            addCriterion("OPERID <", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidLessThanOrEqualTo(String value) {
            addCriterion("OPERID <=", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidLike(String value) {
            addCriterion("OPERID like", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotLike(String value) {
            addCriterion("OPERID not like", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidIn(List<String> values) {
            addCriterion("OPERID in", values, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotIn(List<String> values) {
            addCriterion("OPERID not in", values, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidBetween(String value1, String value2) {
            addCriterion("OPERID between", value1, value2, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotBetween(String value1, String value2) {
            addCriterion("OPERID not between", value1, value2, "operid");
            return (Criteria) this;
        }

        public Criteria andOperdateIsNull() {
            addCriterion("OPERDATE is null");
            return (Criteria) this;
        }

        public Criteria andOperdateIsNotNull() {
            addCriterion("OPERDATE is not null");
            return (Criteria) this;
        }

        public Criteria andOperdateEqualTo(Date value) {
            addCriterion("OPERDATE =", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateNotEqualTo(Date value) {
            addCriterion("OPERDATE <>", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateGreaterThan(Date value) {
            addCriterion("OPERDATE >", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateGreaterThanOrEqualTo(Date value) {
            addCriterion("OPERDATE >=", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateLessThan(Date value) {
            addCriterion("OPERDATE <", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateLessThanOrEqualTo(Date value) {
            addCriterion("OPERDATE <=", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateIn(List<Date> values) {
            addCriterion("OPERDATE in", values, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateNotIn(List<Date> values) {
            addCriterion("OPERDATE not in", values, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateBetween(Date value1, Date value2) {
            addCriterion("OPERDATE between", value1, value2, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateNotBetween(Date value1, Date value2) {
            addCriterion("OPERDATE not between", value1, value2, "operdate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_BASE_BASEINFO
     *
     * @mbggenerated do_not_delete_during_merge Tue Dec 20 16:12:39 CST 2011
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_BASE_BASEINFO
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}