package fis.repository.model;

import java.util.Date;

public class FsPunishconfirm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_PUNISHCONFIRM.PKID
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_PUNISHCONFIRM.NOTICENO
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    private String noticeno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_PUNISHCONFIRM.RECFEEDATE
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    private String recfeedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_PUNISHCONFIRM.BANKRECEIPTNO
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    private String bankreceiptno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_PUNISHCONFIRM.VERSION
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_PUNISHCONFIRM.OPERID
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    private String operid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_PUNISHCONFIRM.OPERDATE
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    private Date operdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_PUNISHCONFIRM.PKID
     *
     * @return the value of FIS.FS_PUNISHCONFIRM.PKID
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_PUNISHCONFIRM.PKID
     *
     * @param pkid the value for FIS.FS_PUNISHCONFIRM.PKID
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_PUNISHCONFIRM.NOTICENO
     *
     * @return the value of FIS.FS_PUNISHCONFIRM.NOTICENO
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public String getNoticeno() {
        return noticeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_PUNISHCONFIRM.NOTICENO
     *
     * @param noticeno the value for FIS.FS_PUNISHCONFIRM.NOTICENO
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public void setNoticeno(String noticeno) {
        this.noticeno = noticeno == null ? null : noticeno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_PUNISHCONFIRM.RECFEEDATE
     *
     * @return the value of FIS.FS_PUNISHCONFIRM.RECFEEDATE
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public String getRecfeedate() {
        return recfeedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_PUNISHCONFIRM.RECFEEDATE
     *
     * @param recfeedate the value for FIS.FS_PUNISHCONFIRM.RECFEEDATE
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public void setRecfeedate(String recfeedate) {
        this.recfeedate = recfeedate == null ? null : recfeedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_PUNISHCONFIRM.BANKRECEIPTNO
     *
     * @return the value of FIS.FS_PUNISHCONFIRM.BANKRECEIPTNO
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public String getBankreceiptno() {
        return bankreceiptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_PUNISHCONFIRM.BANKRECEIPTNO
     *
     * @param bankreceiptno the value for FIS.FS_PUNISHCONFIRM.BANKRECEIPTNO
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public void setBankreceiptno(String bankreceiptno) {
        this.bankreceiptno = bankreceiptno == null ? null : bankreceiptno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_PUNISHCONFIRM.VERSION
     *
     * @return the value of FIS.FS_PUNISHCONFIRM.VERSION
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_PUNISHCONFIRM.VERSION
     *
     * @param version the value for FIS.FS_PUNISHCONFIRM.VERSION
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_PUNISHCONFIRM.OPERID
     *
     * @return the value of FIS.FS_PUNISHCONFIRM.OPERID
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public String getOperid() {
        return operid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_PUNISHCONFIRM.OPERID
     *
     * @param operid the value for FIS.FS_PUNISHCONFIRM.OPERID
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public void setOperid(String operid) {
        this.operid = operid == null ? null : operid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_PUNISHCONFIRM.OPERDATE
     *
     * @return the value of FIS.FS_PUNISHCONFIRM.OPERDATE
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public Date getOperdate() {
        return operdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_PUNISHCONFIRM.OPERDATE
     *
     * @param operdate the value for FIS.FS_PUNISHCONFIRM.OPERDATE
     *
     * @mbggenerated Tue Dec 20 16:12:39 CST 2011
     */
    public void setOperdate(Date operdate) {
        this.operdate = operdate;
    }
}