package fis.repository.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FsPunishnoticeinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_PUNISHNOTICEINFO
     *
     * @mbggenerated Tue Dec 20 16:48:18 CST 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_PUNISHNOTICEINFO
     *
     * @mbggenerated Tue Dec 20 16:48:18 CST 2011
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_PUNISHNOTICEINFO
     *
     * @mbggenerated Tue Dec 20 16:48:18 CST 2011
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_PUNISHNOTICEINFO
     *
     * @mbggenerated Tue Dec 20 16:48:18 CST 2011
     */
    public FsPunishnoticeinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_PUNISHNOTICEINFO
     *
     * @mbggenerated Tue Dec 20 16:48:18 CST 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_PUNISHNOTICEINFO
     *
     * @mbggenerated Tue Dec 20 16:48:18 CST 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_PUNISHNOTICEINFO
     *
     * @mbggenerated Tue Dec 20 16:48:18 CST 2011
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_PUNISHNOTICEINFO
     *
     * @mbggenerated Tue Dec 20 16:48:18 CST 2011
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_PUNISHNOTICEINFO
     *
     * @mbggenerated Tue Dec 20 16:48:18 CST 2011
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_PUNISHNOTICEINFO
     *
     * @mbggenerated Tue Dec 20 16:48:18 CST 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_PUNISHNOTICEINFO
     *
     * @mbggenerated Tue Dec 20 16:48:18 CST 2011
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_PUNISHNOTICEINFO
     *
     * @mbggenerated Tue Dec 20 16:48:18 CST 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_PUNISHNOTICEINFO
     *
     * @mbggenerated Tue Dec 20 16:48:18 CST 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_PUNISHNOTICEINFO
     *
     * @mbggenerated Tue Dec 20 16:48:18 CST 2011
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_PUNISHNOTICEINFO
     *
     * @mbggenerated Tue Dec 20 16:48:18 CST 2011
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andBillidIsNull() {
            addCriterion("BILLID is null");
            return (Criteria) this;
        }

        public Criteria andBillidIsNotNull() {
            addCriterion("BILLID is not null");
            return (Criteria) this;
        }

        public Criteria andBillidEqualTo(Integer value) {
            addCriterion("BILLID =", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidNotEqualTo(Integer value) {
            addCriterion("BILLID <>", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidGreaterThan(Integer value) {
            addCriterion("BILLID >", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidGreaterThanOrEqualTo(Integer value) {
            addCriterion("BILLID >=", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidLessThan(Integer value) {
            addCriterion("BILLID <", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidLessThanOrEqualTo(Integer value) {
            addCriterion("BILLID <=", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidIn(List<Integer> values) {
            addCriterion("BILLID in", values, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidNotIn(List<Integer> values) {
            addCriterion("BILLID not in", values, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidBetween(Integer value1, Integer value2) {
            addCriterion("BILLID between", value1, value2, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidNotBetween(Integer value1, Integer value2) {
            addCriterion("BILLID not between", value1, value2, "billid");
            return (Criteria) this;
        }

        public Criteria andNoticenoIsNull() {
            addCriterion("NOTICENO is null");
            return (Criteria) this;
        }

        public Criteria andNoticenoIsNotNull() {
            addCriterion("NOTICENO is not null");
            return (Criteria) this;
        }

        public Criteria andNoticenoEqualTo(String value) {
            addCriterion("NOTICENO =", value, "noticeno");
            return (Criteria) this;
        }

        public Criteria andNoticenoNotEqualTo(String value) {
            addCriterion("NOTICENO <>", value, "noticeno");
            return (Criteria) this;
        }

        public Criteria andNoticenoGreaterThan(String value) {
            addCriterion("NOTICENO >", value, "noticeno");
            return (Criteria) this;
        }

        public Criteria andNoticenoGreaterThanOrEqualTo(String value) {
            addCriterion("NOTICENO >=", value, "noticeno");
            return (Criteria) this;
        }

        public Criteria andNoticenoLessThan(String value) {
            addCriterion("NOTICENO <", value, "noticeno");
            return (Criteria) this;
        }

        public Criteria andNoticenoLessThanOrEqualTo(String value) {
            addCriterion("NOTICENO <=", value, "noticeno");
            return (Criteria) this;
        }

        public Criteria andNoticenoLike(String value) {
            addCriterion("NOTICENO like", value, "noticeno");
            return (Criteria) this;
        }

        public Criteria andNoticenoNotLike(String value) {
            addCriterion("NOTICENO not like", value, "noticeno");
            return (Criteria) this;
        }

        public Criteria andNoticenoIn(List<String> values) {
            addCriterion("NOTICENO in", values, "noticeno");
            return (Criteria) this;
        }

        public Criteria andNoticenoNotIn(List<String> values) {
            addCriterion("NOTICENO not in", values, "noticeno");
            return (Criteria) this;
        }

        public Criteria andNoticenoBetween(String value1, String value2) {
            addCriterion("NOTICENO between", value1, value2, "noticeno");
            return (Criteria) this;
        }

        public Criteria andNoticenoNotBetween(String value1, String value2) {
            addCriterion("NOTICENO not between", value1, value2, "noticeno");
            return (Criteria) this;
        }

        public Criteria andPayerIsNull() {
            addCriterion("PAYER is null");
            return (Criteria) this;
        }

        public Criteria andPayerIsNotNull() {
            addCriterion("PAYER is not null");
            return (Criteria) this;
        }

        public Criteria andPayerEqualTo(String value) {
            addCriterion("PAYER =", value, "payer");
            return (Criteria) this;
        }

        public Criteria andPayerNotEqualTo(String value) {
            addCriterion("PAYER <>", value, "payer");
            return (Criteria) this;
        }

        public Criteria andPayerGreaterThan(String value) {
            addCriterion("PAYER >", value, "payer");
            return (Criteria) this;
        }

        public Criteria andPayerGreaterThanOrEqualTo(String value) {
            addCriterion("PAYER >=", value, "payer");
            return (Criteria) this;
        }

        public Criteria andPayerLessThan(String value) {
            addCriterion("PAYER <", value, "payer");
            return (Criteria) this;
        }

        public Criteria andPayerLessThanOrEqualTo(String value) {
            addCriterion("PAYER <=", value, "payer");
            return (Criteria) this;
        }

        public Criteria andPayerLike(String value) {
            addCriterion("PAYER like", value, "payer");
            return (Criteria) this;
        }

        public Criteria andPayerNotLike(String value) {
            addCriterion("PAYER not like", value, "payer");
            return (Criteria) this;
        }

        public Criteria andPayerIn(List<String> values) {
            addCriterion("PAYER in", values, "payer");
            return (Criteria) this;
        }

        public Criteria andPayerNotIn(List<String> values) {
            addCriterion("PAYER not in", values, "payer");
            return (Criteria) this;
        }

        public Criteria andPayerBetween(String value1, String value2) {
            addCriterion("PAYER between", value1, value2, "payer");
            return (Criteria) this;
        }

        public Criteria andPayerNotBetween(String value1, String value2) {
            addCriterion("PAYER not between", value1, value2, "payer");
            return (Criteria) this;
        }

        public Criteria andPfdeptcodeIsNull() {
            addCriterion("PFDEPTCODE is null");
            return (Criteria) this;
        }

        public Criteria andPfdeptcodeIsNotNull() {
            addCriterion("PFDEPTCODE is not null");
            return (Criteria) this;
        }

        public Criteria andPfdeptcodeEqualTo(String value) {
            addCriterion("PFDEPTCODE =", value, "pfdeptcode");
            return (Criteria) this;
        }

        public Criteria andPfdeptcodeNotEqualTo(String value) {
            addCriterion("PFDEPTCODE <>", value, "pfdeptcode");
            return (Criteria) this;
        }

        public Criteria andPfdeptcodeGreaterThan(String value) {
            addCriterion("PFDEPTCODE >", value, "pfdeptcode");
            return (Criteria) this;
        }

        public Criteria andPfdeptcodeGreaterThanOrEqualTo(String value) {
            addCriterion("PFDEPTCODE >=", value, "pfdeptcode");
            return (Criteria) this;
        }

        public Criteria andPfdeptcodeLessThan(String value) {
            addCriterion("PFDEPTCODE <", value, "pfdeptcode");
            return (Criteria) this;
        }

        public Criteria andPfdeptcodeLessThanOrEqualTo(String value) {
            addCriterion("PFDEPTCODE <=", value, "pfdeptcode");
            return (Criteria) this;
        }

        public Criteria andPfdeptcodeLike(String value) {
            addCriterion("PFDEPTCODE like", value, "pfdeptcode");
            return (Criteria) this;
        }

        public Criteria andPfdeptcodeNotLike(String value) {
            addCriterion("PFDEPTCODE not like", value, "pfdeptcode");
            return (Criteria) this;
        }

        public Criteria andPfdeptcodeIn(List<String> values) {
            addCriterion("PFDEPTCODE in", values, "pfdeptcode");
            return (Criteria) this;
        }

        public Criteria andPfdeptcodeNotIn(List<String> values) {
            addCriterion("PFDEPTCODE not in", values, "pfdeptcode");
            return (Criteria) this;
        }

        public Criteria andPfdeptcodeBetween(String value1, String value2) {
            addCriterion("PFDEPTCODE between", value1, value2, "pfdeptcode");
            return (Criteria) this;
        }

        public Criteria andPfdeptcodeNotBetween(String value1, String value2) {
            addCriterion("PFDEPTCODE not between", value1, value2, "pfdeptcode");
            return (Criteria) this;
        }

        public Criteria andPunishdecnoIsNull() {
            addCriterion("PUNISHDECNO is null");
            return (Criteria) this;
        }

        public Criteria andPunishdecnoIsNotNull() {
            addCriterion("PUNISHDECNO is not null");
            return (Criteria) this;
        }

        public Criteria andPunishdecnoEqualTo(String value) {
            addCriterion("PUNISHDECNO =", value, "punishdecno");
            return (Criteria) this;
        }

        public Criteria andPunishdecnoNotEqualTo(String value) {
            addCriterion("PUNISHDECNO <>", value, "punishdecno");
            return (Criteria) this;
        }

        public Criteria andPunishdecnoGreaterThan(String value) {
            addCriterion("PUNISHDECNO >", value, "punishdecno");
            return (Criteria) this;
        }

        public Criteria andPunishdecnoGreaterThanOrEqualTo(String value) {
            addCriterion("PUNISHDECNO >=", value, "punishdecno");
            return (Criteria) this;
        }

        public Criteria andPunishdecnoLessThan(String value) {
            addCriterion("PUNISHDECNO <", value, "punishdecno");
            return (Criteria) this;
        }

        public Criteria andPunishdecnoLessThanOrEqualTo(String value) {
            addCriterion("PUNISHDECNO <=", value, "punishdecno");
            return (Criteria) this;
        }

        public Criteria andPunishdecnoLike(String value) {
            addCriterion("PUNISHDECNO like", value, "punishdecno");
            return (Criteria) this;
        }

        public Criteria andPunishdecnoNotLike(String value) {
            addCriterion("PUNISHDECNO not like", value, "punishdecno");
            return (Criteria) this;
        }

        public Criteria andPunishdecnoIn(List<String> values) {
            addCriterion("PUNISHDECNO in", values, "punishdecno");
            return (Criteria) this;
        }

        public Criteria andPunishdecnoNotIn(List<String> values) {
            addCriterion("PUNISHDECNO not in", values, "punishdecno");
            return (Criteria) this;
        }

        public Criteria andPunishdecnoBetween(String value1, String value2) {
            addCriterion("PUNISHDECNO between", value1, value2, "punishdecno");
            return (Criteria) this;
        }

        public Criteria andPunishdecnoNotBetween(String value1, String value2) {
            addCriterion("PUNISHDECNO not between", value1, value2, "punishdecno");
            return (Criteria) this;
        }

        public Criteria andAmtIsNull() {
            addCriterion("AMT is null");
            return (Criteria) this;
        }

        public Criteria andAmtIsNotNull() {
            addCriterion("AMT is not null");
            return (Criteria) this;
        }

        public Criteria andAmtEqualTo(BigDecimal value) {
            addCriterion("AMT =", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotEqualTo(BigDecimal value) {
            addCriterion("AMT <>", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtGreaterThan(BigDecimal value) {
            addCriterion("AMT >", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AMT >=", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtLessThan(BigDecimal value) {
            addCriterion("AMT <", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AMT <=", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtIn(List<BigDecimal> values) {
            addCriterion("AMT in", values, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotIn(List<BigDecimal> values) {
            addCriterion("AMT not in", values, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AMT between", value1, value2, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AMT not between", value1, value2, "amt");
            return (Criteria) this;
        }

        public Criteria andPaycycleIsNull() {
            addCriterion("PAYCYCLE is null");
            return (Criteria) this;
        }

        public Criteria andPaycycleIsNotNull() {
            addCriterion("PAYCYCLE is not null");
            return (Criteria) this;
        }

        public Criteria andPaycycleEqualTo(String value) {
            addCriterion("PAYCYCLE =", value, "paycycle");
            return (Criteria) this;
        }

        public Criteria andPaycycleNotEqualTo(String value) {
            addCriterion("PAYCYCLE <>", value, "paycycle");
            return (Criteria) this;
        }

        public Criteria andPaycycleGreaterThan(String value) {
            addCriterion("PAYCYCLE >", value, "paycycle");
            return (Criteria) this;
        }

        public Criteria andPaycycleGreaterThanOrEqualTo(String value) {
            addCriterion("PAYCYCLE >=", value, "paycycle");
            return (Criteria) this;
        }

        public Criteria andPaycycleLessThan(String value) {
            addCriterion("PAYCYCLE <", value, "paycycle");
            return (Criteria) this;
        }

        public Criteria andPaycycleLessThanOrEqualTo(String value) {
            addCriterion("PAYCYCLE <=", value, "paycycle");
            return (Criteria) this;
        }

        public Criteria andPaycycleLike(String value) {
            addCriterion("PAYCYCLE like", value, "paycycle");
            return (Criteria) this;
        }

        public Criteria andPaycycleNotLike(String value) {
            addCriterion("PAYCYCLE not like", value, "paycycle");
            return (Criteria) this;
        }

        public Criteria andPaycycleIn(List<String> values) {
            addCriterion("PAYCYCLE in", values, "paycycle");
            return (Criteria) this;
        }

        public Criteria andPaycycleNotIn(List<String> values) {
            addCriterion("PAYCYCLE not in", values, "paycycle");
            return (Criteria) this;
        }

        public Criteria andPaycycleBetween(String value1, String value2) {
            addCriterion("PAYCYCLE between", value1, value2, "paycycle");
            return (Criteria) this;
        }

        public Criteria andPaycycleNotBetween(String value1, String value2) {
            addCriterion("PAYCYCLE not between", value1, value2, "paycycle");
            return (Criteria) this;
        }

        public Criteria andEnddateIsNull() {
            addCriterion("ENDDATE is null");
            return (Criteria) this;
        }

        public Criteria andEnddateIsNotNull() {
            addCriterion("ENDDATE is not null");
            return (Criteria) this;
        }

        public Criteria andEnddateEqualTo(String value) {
            addCriterion("ENDDATE =", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotEqualTo(String value) {
            addCriterion("ENDDATE <>", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateGreaterThan(String value) {
            addCriterion("ENDDATE >", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateGreaterThanOrEqualTo(String value) {
            addCriterion("ENDDATE >=", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateLessThan(String value) {
            addCriterion("ENDDATE <", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateLessThanOrEqualTo(String value) {
            addCriterion("ENDDATE <=", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateLike(String value) {
            addCriterion("ENDDATE like", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotLike(String value) {
            addCriterion("ENDDATE not like", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateIn(List<String> values) {
            addCriterion("ENDDATE in", values, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotIn(List<String> values) {
            addCriterion("ENDDATE not in", values, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateBetween(String value1, String value2) {
            addCriterion("ENDDATE between", value1, value2, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotBetween(String value1, String value2) {
            addCriterion("ENDDATE not between", value1, value2, "enddate");
            return (Criteria) this;
        }

        public Criteria andPerformdeptIsNull() {
            addCriterion("PERFORMDEPT is null");
            return (Criteria) this;
        }

        public Criteria andPerformdeptIsNotNull() {
            addCriterion("PERFORMDEPT is not null");
            return (Criteria) this;
        }

        public Criteria andPerformdeptEqualTo(String value) {
            addCriterion("PERFORMDEPT =", value, "performdept");
            return (Criteria) this;
        }

        public Criteria andPerformdeptNotEqualTo(String value) {
            addCriterion("PERFORMDEPT <>", value, "performdept");
            return (Criteria) this;
        }

        public Criteria andPerformdeptGreaterThan(String value) {
            addCriterion("PERFORMDEPT >", value, "performdept");
            return (Criteria) this;
        }

        public Criteria andPerformdeptGreaterThanOrEqualTo(String value) {
            addCriterion("PERFORMDEPT >=", value, "performdept");
            return (Criteria) this;
        }

        public Criteria andPerformdeptLessThan(String value) {
            addCriterion("PERFORMDEPT <", value, "performdept");
            return (Criteria) this;
        }

        public Criteria andPerformdeptLessThanOrEqualTo(String value) {
            addCriterion("PERFORMDEPT <=", value, "performdept");
            return (Criteria) this;
        }

        public Criteria andPerformdeptLike(String value) {
            addCriterion("PERFORMDEPT like", value, "performdept");
            return (Criteria) this;
        }

        public Criteria andPerformdeptNotLike(String value) {
            addCriterion("PERFORMDEPT not like", value, "performdept");
            return (Criteria) this;
        }

        public Criteria andPerformdeptIn(List<String> values) {
            addCriterion("PERFORMDEPT in", values, "performdept");
            return (Criteria) this;
        }

        public Criteria andPerformdeptNotIn(List<String> values) {
            addCriterion("PERFORMDEPT not in", values, "performdept");
            return (Criteria) this;
        }

        public Criteria andPerformdeptBetween(String value1, String value2) {
            addCriterion("PERFORMDEPT between", value1, value2, "performdept");
            return (Criteria) this;
        }

        public Criteria andPerformdeptNotBetween(String value1, String value2) {
            addCriterion("PERFORMDEPT not between", value1, value2, "performdept");
            return (Criteria) this;
        }

        public Criteria andLatefeepercentIsNull() {
            addCriterion("LATEFEEPERCENT is null");
            return (Criteria) this;
        }

        public Criteria andLatefeepercentIsNotNull() {
            addCriterion("LATEFEEPERCENT is not null");
            return (Criteria) this;
        }

        public Criteria andLatefeepercentEqualTo(String value) {
            addCriterion("LATEFEEPERCENT =", value, "latefeepercent");
            return (Criteria) this;
        }

        public Criteria andLatefeepercentNotEqualTo(String value) {
            addCriterion("LATEFEEPERCENT <>", value, "latefeepercent");
            return (Criteria) this;
        }

        public Criteria andLatefeepercentGreaterThan(String value) {
            addCriterion("LATEFEEPERCENT >", value, "latefeepercent");
            return (Criteria) this;
        }

        public Criteria andLatefeepercentGreaterThanOrEqualTo(String value) {
            addCriterion("LATEFEEPERCENT >=", value, "latefeepercent");
            return (Criteria) this;
        }

        public Criteria andLatefeepercentLessThan(String value) {
            addCriterion("LATEFEEPERCENT <", value, "latefeepercent");
            return (Criteria) this;
        }

        public Criteria andLatefeepercentLessThanOrEqualTo(String value) {
            addCriterion("LATEFEEPERCENT <=", value, "latefeepercent");
            return (Criteria) this;
        }

        public Criteria andLatefeepercentLike(String value) {
            addCriterion("LATEFEEPERCENT like", value, "latefeepercent");
            return (Criteria) this;
        }

        public Criteria andLatefeepercentNotLike(String value) {
            addCriterion("LATEFEEPERCENT not like", value, "latefeepercent");
            return (Criteria) this;
        }

        public Criteria andLatefeepercentIn(List<String> values) {
            addCriterion("LATEFEEPERCENT in", values, "latefeepercent");
            return (Criteria) this;
        }

        public Criteria andLatefeepercentNotIn(List<String> values) {
            addCriterion("LATEFEEPERCENT not in", values, "latefeepercent");
            return (Criteria) this;
        }

        public Criteria andLatefeepercentBetween(String value1, String value2) {
            addCriterion("LATEFEEPERCENT between", value1, value2, "latefeepercent");
            return (Criteria) this;
        }

        public Criteria andLatefeepercentNotBetween(String value1, String value2) {
            addCriterion("LATEFEEPERCENT not between", value1, value2, "latefeepercent");
            return (Criteria) this;
        }

        public Criteria andPfdeptnameIsNull() {
            addCriterion("PFDEPTNAME is null");
            return (Criteria) this;
        }

        public Criteria andPfdeptnameIsNotNull() {
            addCriterion("PFDEPTNAME is not null");
            return (Criteria) this;
        }

        public Criteria andPfdeptnameEqualTo(String value) {
            addCriterion("PFDEPTNAME =", value, "pfdeptname");
            return (Criteria) this;
        }

        public Criteria andPfdeptnameNotEqualTo(String value) {
            addCriterion("PFDEPTNAME <>", value, "pfdeptname");
            return (Criteria) this;
        }

        public Criteria andPfdeptnameGreaterThan(String value) {
            addCriterion("PFDEPTNAME >", value, "pfdeptname");
            return (Criteria) this;
        }

        public Criteria andPfdeptnameGreaterThanOrEqualTo(String value) {
            addCriterion("PFDEPTNAME >=", value, "pfdeptname");
            return (Criteria) this;
        }

        public Criteria andPfdeptnameLessThan(String value) {
            addCriterion("PFDEPTNAME <", value, "pfdeptname");
            return (Criteria) this;
        }

        public Criteria andPfdeptnameLessThanOrEqualTo(String value) {
            addCriterion("PFDEPTNAME <=", value, "pfdeptname");
            return (Criteria) this;
        }

        public Criteria andPfdeptnameLike(String value) {
            addCriterion("PFDEPTNAME like", value, "pfdeptname");
            return (Criteria) this;
        }

        public Criteria andPfdeptnameNotLike(String value) {
            addCriterion("PFDEPTNAME not like", value, "pfdeptname");
            return (Criteria) this;
        }

        public Criteria andPfdeptnameIn(List<String> values) {
            addCriterion("PFDEPTNAME in", values, "pfdeptname");
            return (Criteria) this;
        }

        public Criteria andPfdeptnameNotIn(List<String> values) {
            addCriterion("PFDEPTNAME not in", values, "pfdeptname");
            return (Criteria) this;
        }

        public Criteria andPfdeptnameBetween(String value1, String value2) {
            addCriterion("PFDEPTNAME between", value1, value2, "pfdeptname");
            return (Criteria) this;
        }

        public Criteria andPfdeptnameNotBetween(String value1, String value2) {
            addCriterion("PFDEPTNAME not between", value1, value2, "pfdeptname");
            return (Criteria) this;
        }

        public Criteria andPolicemanIsNull() {
            addCriterion("POLICEMAN is null");
            return (Criteria) this;
        }

        public Criteria andPolicemanIsNotNull() {
            addCriterion("POLICEMAN is not null");
            return (Criteria) this;
        }

        public Criteria andPolicemanEqualTo(String value) {
            addCriterion("POLICEMAN =", value, "policeman");
            return (Criteria) this;
        }

        public Criteria andPolicemanNotEqualTo(String value) {
            addCriterion("POLICEMAN <>", value, "policeman");
            return (Criteria) this;
        }

        public Criteria andPolicemanGreaterThan(String value) {
            addCriterion("POLICEMAN >", value, "policeman");
            return (Criteria) this;
        }

        public Criteria andPolicemanGreaterThanOrEqualTo(String value) {
            addCriterion("POLICEMAN >=", value, "policeman");
            return (Criteria) this;
        }

        public Criteria andPolicemanLessThan(String value) {
            addCriterion("POLICEMAN <", value, "policeman");
            return (Criteria) this;
        }

        public Criteria andPolicemanLessThanOrEqualTo(String value) {
            addCriterion("POLICEMAN <=", value, "policeman");
            return (Criteria) this;
        }

        public Criteria andPolicemanLike(String value) {
            addCriterion("POLICEMAN like", value, "policeman");
            return (Criteria) this;
        }

        public Criteria andPolicemanNotLike(String value) {
            addCriterion("POLICEMAN not like", value, "policeman");
            return (Criteria) this;
        }

        public Criteria andPolicemanIn(List<String> values) {
            addCriterion("POLICEMAN in", values, "policeman");
            return (Criteria) this;
        }

        public Criteria andPolicemanNotIn(List<String> values) {
            addCriterion("POLICEMAN not in", values, "policeman");
            return (Criteria) this;
        }

        public Criteria andPolicemanBetween(String value1, String value2) {
            addCriterion("POLICEMAN between", value1, value2, "policeman");
            return (Criteria) this;
        }

        public Criteria andPolicemanNotBetween(String value1, String value2) {
            addCriterion("POLICEMAN not between", value1, value2, "policeman");
            return (Criteria) this;
        }

        public Criteria andNoticedateIsNull() {
            addCriterion("NOTICEDATE is null");
            return (Criteria) this;
        }

        public Criteria andNoticedateIsNotNull() {
            addCriterion("NOTICEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andNoticedateEqualTo(String value) {
            addCriterion("NOTICEDATE =", value, "noticedate");
            return (Criteria) this;
        }

        public Criteria andNoticedateNotEqualTo(String value) {
            addCriterion("NOTICEDATE <>", value, "noticedate");
            return (Criteria) this;
        }

        public Criteria andNoticedateGreaterThan(String value) {
            addCriterion("NOTICEDATE >", value, "noticedate");
            return (Criteria) this;
        }

        public Criteria andNoticedateGreaterThanOrEqualTo(String value) {
            addCriterion("NOTICEDATE >=", value, "noticedate");
            return (Criteria) this;
        }

        public Criteria andNoticedateLessThan(String value) {
            addCriterion("NOTICEDATE <", value, "noticedate");
            return (Criteria) this;
        }

        public Criteria andNoticedateLessThanOrEqualTo(String value) {
            addCriterion("NOTICEDATE <=", value, "noticedate");
            return (Criteria) this;
        }

        public Criteria andNoticedateLike(String value) {
            addCriterion("NOTICEDATE like", value, "noticedate");
            return (Criteria) this;
        }

        public Criteria andNoticedateNotLike(String value) {
            addCriterion("NOTICEDATE not like", value, "noticedate");
            return (Criteria) this;
        }

        public Criteria andNoticedateIn(List<String> values) {
            addCriterion("NOTICEDATE in", values, "noticedate");
            return (Criteria) this;
        }

        public Criteria andNoticedateNotIn(List<String> values) {
            addCriterion("NOTICEDATE not in", values, "noticedate");
            return (Criteria) this;
        }

        public Criteria andNoticedateBetween(String value1, String value2) {
            addCriterion("NOTICEDATE between", value1, value2, "noticedate");
            return (Criteria) this;
        }

        public Criteria andNoticedateNotBetween(String value1, String value2) {
            addCriterion("NOTICEDATE not between", value1, value2, "noticedate");
            return (Criteria) this;
        }

        public Criteria andCreateuserIsNull() {
            addCriterion("CREATEUSER is null");
            return (Criteria) this;
        }

        public Criteria andCreateuserIsNotNull() {
            addCriterion("CREATEUSER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateuserEqualTo(String value) {
            addCriterion("CREATEUSER =", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotEqualTo(String value) {
            addCriterion("CREATEUSER <>", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserGreaterThan(String value) {
            addCriterion("CREATEUSER >", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEUSER >=", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLessThan(String value) {
            addCriterion("CREATEUSER <", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLessThanOrEqualTo(String value) {
            addCriterion("CREATEUSER <=", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLike(String value) {
            addCriterion("CREATEUSER like", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotLike(String value) {
            addCriterion("CREATEUSER not like", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserIn(List<String> values) {
            addCriterion("CREATEUSER in", values, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotIn(List<String> values) {
            addCriterion("CREATEUSER not in", values, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserBetween(String value1, String value2) {
            addCriterion("CREATEUSER between", value1, value2, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotBetween(String value1, String value2) {
            addCriterion("CREATEUSER not between", value1, value2, "createuser");
            return (Criteria) this;
        }

        public Criteria andBankreceiptnoIsNull() {
            addCriterion("BANKRECEIPTNO is null");
            return (Criteria) this;
        }

        public Criteria andBankreceiptnoIsNotNull() {
            addCriterion("BANKRECEIPTNO is not null");
            return (Criteria) this;
        }

        public Criteria andBankreceiptnoEqualTo(String value) {
            addCriterion("BANKRECEIPTNO =", value, "bankreceiptno");
            return (Criteria) this;
        }

        public Criteria andBankreceiptnoNotEqualTo(String value) {
            addCriterion("BANKRECEIPTNO <>", value, "bankreceiptno");
            return (Criteria) this;
        }

        public Criteria andBankreceiptnoGreaterThan(String value) {
            addCriterion("BANKRECEIPTNO >", value, "bankreceiptno");
            return (Criteria) this;
        }

        public Criteria andBankreceiptnoGreaterThanOrEqualTo(String value) {
            addCriterion("BANKRECEIPTNO >=", value, "bankreceiptno");
            return (Criteria) this;
        }

        public Criteria andBankreceiptnoLessThan(String value) {
            addCriterion("BANKRECEIPTNO <", value, "bankreceiptno");
            return (Criteria) this;
        }

        public Criteria andBankreceiptnoLessThanOrEqualTo(String value) {
            addCriterion("BANKRECEIPTNO <=", value, "bankreceiptno");
            return (Criteria) this;
        }

        public Criteria andBankreceiptnoLike(String value) {
            addCriterion("BANKRECEIPTNO like", value, "bankreceiptno");
            return (Criteria) this;
        }

        public Criteria andBankreceiptnoNotLike(String value) {
            addCriterion("BANKRECEIPTNO not like", value, "bankreceiptno");
            return (Criteria) this;
        }

        public Criteria andBankreceiptnoIn(List<String> values) {
            addCriterion("BANKRECEIPTNO in", values, "bankreceiptno");
            return (Criteria) this;
        }

        public Criteria andBankreceiptnoNotIn(List<String> values) {
            addCriterion("BANKRECEIPTNO not in", values, "bankreceiptno");
            return (Criteria) this;
        }

        public Criteria andBankreceiptnoBetween(String value1, String value2) {
            addCriterion("BANKRECEIPTNO between", value1, value2, "bankreceiptno");
            return (Criteria) this;
        }

        public Criteria andBankreceiptnoNotBetween(String value1, String value2) {
            addCriterion("BANKRECEIPTNO not between", value1, value2, "bankreceiptno");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagIsNull() {
            addCriterion("RECFEEFLAG is null");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagIsNotNull() {
            addCriterion("RECFEEFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagEqualTo(String value) {
            addCriterion("RECFEEFLAG =", value, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagNotEqualTo(String value) {
            addCriterion("RECFEEFLAG <>", value, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagGreaterThan(String value) {
            addCriterion("RECFEEFLAG >", value, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagGreaterThanOrEqualTo(String value) {
            addCriterion("RECFEEFLAG >=", value, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagLessThan(String value) {
            addCriterion("RECFEEFLAG <", value, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagLessThanOrEqualTo(String value) {
            addCriterion("RECFEEFLAG <=", value, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagLike(String value) {
            addCriterion("RECFEEFLAG like", value, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagNotLike(String value) {
            addCriterion("RECFEEFLAG not like", value, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagIn(List<String> values) {
            addCriterion("RECFEEFLAG in", values, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagNotIn(List<String> values) {
            addCriterion("RECFEEFLAG not in", values, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagBetween(String value1, String value2) {
            addCriterion("RECFEEFLAG between", value1, value2, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeeflagNotBetween(String value1, String value2) {
            addCriterion("RECFEEFLAG not between", value1, value2, "recfeeflag");
            return (Criteria) this;
        }

        public Criteria andRecfeedateIsNull() {
            addCriterion("RECFEEDATE is null");
            return (Criteria) this;
        }

        public Criteria andRecfeedateIsNotNull() {
            addCriterion("RECFEEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andRecfeedateEqualTo(String value) {
            addCriterion("RECFEEDATE =", value, "recfeedate");
            return (Criteria) this;
        }

        public Criteria andRecfeedateNotEqualTo(String value) {
            addCriterion("RECFEEDATE <>", value, "recfeedate");
            return (Criteria) this;
        }

        public Criteria andRecfeedateGreaterThan(String value) {
            addCriterion("RECFEEDATE >", value, "recfeedate");
            return (Criteria) this;
        }

        public Criteria andRecfeedateGreaterThanOrEqualTo(String value) {
            addCriterion("RECFEEDATE >=", value, "recfeedate");
            return (Criteria) this;
        }

        public Criteria andRecfeedateLessThan(String value) {
            addCriterion("RECFEEDATE <", value, "recfeedate");
            return (Criteria) this;
        }

        public Criteria andRecfeedateLessThanOrEqualTo(String value) {
            addCriterion("RECFEEDATE <=", value, "recfeedate");
            return (Criteria) this;
        }

        public Criteria andRecfeedateLike(String value) {
            addCriterion("RECFEEDATE like", value, "recfeedate");
            return (Criteria) this;
        }

        public Criteria andRecfeedateNotLike(String value) {
            addCriterion("RECFEEDATE not like", value, "recfeedate");
            return (Criteria) this;
        }

        public Criteria andRecfeedateIn(List<String> values) {
            addCriterion("RECFEEDATE in", values, "recfeedate");
            return (Criteria) this;
        }

        public Criteria andRecfeedateNotIn(List<String> values) {
            addCriterion("RECFEEDATE not in", values, "recfeedate");
            return (Criteria) this;
        }

        public Criteria andRecfeedateBetween(String value1, String value2) {
            addCriterion("RECFEEDATE between", value1, value2, "recfeedate");
            return (Criteria) this;
        }

        public Criteria andRecfeedateNotBetween(String value1, String value2) {
            addCriterion("RECFEEDATE not between", value1, value2, "recfeedate");
            return (Criteria) this;
        }

        public Criteria andPerformdeptidIsNull() {
            addCriterion("PERFORMDEPTID is null");
            return (Criteria) this;
        }

        public Criteria andPerformdeptidIsNotNull() {
            addCriterion("PERFORMDEPTID is not null");
            return (Criteria) this;
        }

        public Criteria andPerformdeptidEqualTo(Integer value) {
            addCriterion("PERFORMDEPTID =", value, "performdeptid");
            return (Criteria) this;
        }

        public Criteria andPerformdeptidNotEqualTo(Integer value) {
            addCriterion("PERFORMDEPTID <>", value, "performdeptid");
            return (Criteria) this;
        }

        public Criteria andPerformdeptidGreaterThan(Integer value) {
            addCriterion("PERFORMDEPTID >", value, "performdeptid");
            return (Criteria) this;
        }

        public Criteria andPerformdeptidGreaterThanOrEqualTo(Integer value) {
            addCriterion("PERFORMDEPTID >=", value, "performdeptid");
            return (Criteria) this;
        }

        public Criteria andPerformdeptidLessThan(Integer value) {
            addCriterion("PERFORMDEPTID <", value, "performdeptid");
            return (Criteria) this;
        }

        public Criteria andPerformdeptidLessThanOrEqualTo(Integer value) {
            addCriterion("PERFORMDEPTID <=", value, "performdeptid");
            return (Criteria) this;
        }

        public Criteria andPerformdeptidIn(List<Integer> values) {
            addCriterion("PERFORMDEPTID in", values, "performdeptid");
            return (Criteria) this;
        }

        public Criteria andPerformdeptidNotIn(List<Integer> values) {
            addCriterion("PERFORMDEPTID not in", values, "performdeptid");
            return (Criteria) this;
        }

        public Criteria andPerformdeptidBetween(Integer value1, Integer value2) {
            addCriterion("PERFORMDEPTID between", value1, value2, "performdeptid");
            return (Criteria) this;
        }

        public Criteria andPerformdeptidNotBetween(Integer value1, Integer value2) {
            addCriterion("PERFORMDEPTID not between", value1, value2, "performdeptid");
            return (Criteria) this;
        }

        public Criteria andPrinttagIsNull() {
            addCriterion("PRINTTAG is null");
            return (Criteria) this;
        }

        public Criteria andPrinttagIsNotNull() {
            addCriterion("PRINTTAG is not null");
            return (Criteria) this;
        }

        public Criteria andPrinttagEqualTo(String value) {
            addCriterion("PRINTTAG =", value, "printtag");
            return (Criteria) this;
        }

        public Criteria andPrinttagNotEqualTo(String value) {
            addCriterion("PRINTTAG <>", value, "printtag");
            return (Criteria) this;
        }

        public Criteria andPrinttagGreaterThan(String value) {
            addCriterion("PRINTTAG >", value, "printtag");
            return (Criteria) this;
        }

        public Criteria andPrinttagGreaterThanOrEqualTo(String value) {
            addCriterion("PRINTTAG >=", value, "printtag");
            return (Criteria) this;
        }

        public Criteria andPrinttagLessThan(String value) {
            addCriterion("PRINTTAG <", value, "printtag");
            return (Criteria) this;
        }

        public Criteria andPrinttagLessThanOrEqualTo(String value) {
            addCriterion("PRINTTAG <=", value, "printtag");
            return (Criteria) this;
        }

        public Criteria andPrinttagLike(String value) {
            addCriterion("PRINTTAG like", value, "printtag");
            return (Criteria) this;
        }

        public Criteria andPrinttagNotLike(String value) {
            addCriterion("PRINTTAG not like", value, "printtag");
            return (Criteria) this;
        }

        public Criteria andPrinttagIn(List<String> values) {
            addCriterion("PRINTTAG in", values, "printtag");
            return (Criteria) this;
        }

        public Criteria andPrinttagNotIn(List<String> values) {
            addCriterion("PRINTTAG not in", values, "printtag");
            return (Criteria) this;
        }

        public Criteria andPrinttagBetween(String value1, String value2) {
            addCriterion("PRINTTAG between", value1, value2, "printtag");
            return (Criteria) this;
        }

        public Criteria andPrinttagNotBetween(String value1, String value2) {
            addCriterion("PRINTTAG not between", value1, value2, "printtag");
            return (Criteria) this;
        }

        public Criteria andCheckcodeIsNull() {
            addCriterion("CHECKCODE is null");
            return (Criteria) this;
        }

        public Criteria andCheckcodeIsNotNull() {
            addCriterion("CHECKCODE is not null");
            return (Criteria) this;
        }

        public Criteria andCheckcodeEqualTo(String value) {
            addCriterion("CHECKCODE =", value, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeNotEqualTo(String value) {
            addCriterion("CHECKCODE <>", value, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeGreaterThan(String value) {
            addCriterion("CHECKCODE >", value, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeGreaterThanOrEqualTo(String value) {
            addCriterion("CHECKCODE >=", value, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeLessThan(String value) {
            addCriterion("CHECKCODE <", value, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeLessThanOrEqualTo(String value) {
            addCriterion("CHECKCODE <=", value, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeLike(String value) {
            addCriterion("CHECKCODE like", value, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeNotLike(String value) {
            addCriterion("CHECKCODE not like", value, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeIn(List<String> values) {
            addCriterion("CHECKCODE in", values, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeNotIn(List<String> values) {
            addCriterion("CHECKCODE not in", values, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeBetween(String value1, String value2) {
            addCriterion("CHECKCODE between", value1, value2, "checkcode");
            return (Criteria) this;
        }

        public Criteria andCheckcodeNotBetween(String value1, String value2) {
            addCriterion("CHECKCODE not between", value1, value2, "checkcode");
            return (Criteria) this;
        }

        public Criteria andRecfeeconfirmIsNull() {
            addCriterion("RECFEECONFIRM is null");
            return (Criteria) this;
        }

        public Criteria andRecfeeconfirmIsNotNull() {
            addCriterion("RECFEECONFIRM is not null");
            return (Criteria) this;
        }

        public Criteria andRecfeeconfirmEqualTo(String value) {
            addCriterion("RECFEECONFIRM =", value, "recfeeconfirm");
            return (Criteria) this;
        }

        public Criteria andRecfeeconfirmNotEqualTo(String value) {
            addCriterion("RECFEECONFIRM <>", value, "recfeeconfirm");
            return (Criteria) this;
        }

        public Criteria andRecfeeconfirmGreaterThan(String value) {
            addCriterion("RECFEECONFIRM >", value, "recfeeconfirm");
            return (Criteria) this;
        }

        public Criteria andRecfeeconfirmGreaterThanOrEqualTo(String value) {
            addCriterion("RECFEECONFIRM >=", value, "recfeeconfirm");
            return (Criteria) this;
        }

        public Criteria andRecfeeconfirmLessThan(String value) {
            addCriterion("RECFEECONFIRM <", value, "recfeeconfirm");
            return (Criteria) this;
        }

        public Criteria andRecfeeconfirmLessThanOrEqualTo(String value) {
            addCriterion("RECFEECONFIRM <=", value, "recfeeconfirm");
            return (Criteria) this;
        }

        public Criteria andRecfeeconfirmLike(String value) {
            addCriterion("RECFEECONFIRM like", value, "recfeeconfirm");
            return (Criteria) this;
        }

        public Criteria andRecfeeconfirmNotLike(String value) {
            addCriterion("RECFEECONFIRM not like", value, "recfeeconfirm");
            return (Criteria) this;
        }

        public Criteria andRecfeeconfirmIn(List<String> values) {
            addCriterion("RECFEECONFIRM in", values, "recfeeconfirm");
            return (Criteria) this;
        }

        public Criteria andRecfeeconfirmNotIn(List<String> values) {
            addCriterion("RECFEECONFIRM not in", values, "recfeeconfirm");
            return (Criteria) this;
        }

        public Criteria andRecfeeconfirmBetween(String value1, String value2) {
            addCriterion("RECFEECONFIRM between", value1, value2, "recfeeconfirm");
            return (Criteria) this;
        }

        public Criteria andRecfeeconfirmNotBetween(String value1, String value2) {
            addCriterion("RECFEECONFIRM not between", value1, value2, "recfeeconfirm");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("VERSION is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("VERSION =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("VERSION <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("VERSION >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("VERSION >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("VERSION <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("VERSION <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("VERSION in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("VERSION not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("VERSION between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("VERSION not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andOperidIsNull() {
            addCriterion("OPERID is null");
            return (Criteria) this;
        }

        public Criteria andOperidIsNotNull() {
            addCriterion("OPERID is not null");
            return (Criteria) this;
        }

        public Criteria andOperidEqualTo(String value) {
            addCriterion("OPERID =", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotEqualTo(String value) {
            addCriterion("OPERID <>", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidGreaterThan(String value) {
            addCriterion("OPERID >", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidGreaterThanOrEqualTo(String value) {
            addCriterion("OPERID >=", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidLessThan(String value) {
            addCriterion("OPERID <", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidLessThanOrEqualTo(String value) {
            addCriterion("OPERID <=", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidLike(String value) {
            addCriterion("OPERID like", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotLike(String value) {
            addCriterion("OPERID not like", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidIn(List<String> values) {
            addCriterion("OPERID in", values, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotIn(List<String> values) {
            addCriterion("OPERID not in", values, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidBetween(String value1, String value2) {
            addCriterion("OPERID between", value1, value2, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotBetween(String value1, String value2) {
            addCriterion("OPERID not between", value1, value2, "operid");
            return (Criteria) this;
        }

        public Criteria andOperdateIsNull() {
            addCriterion("OPERDATE is null");
            return (Criteria) this;
        }

        public Criteria andOperdateIsNotNull() {
            addCriterion("OPERDATE is not null");
            return (Criteria) this;
        }

        public Criteria andOperdateEqualTo(Date value) {
            addCriterion("OPERDATE =", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateNotEqualTo(Date value) {
            addCriterion("OPERDATE <>", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateGreaterThan(Date value) {
            addCriterion("OPERDATE >", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateGreaterThanOrEqualTo(Date value) {
            addCriterion("OPERDATE >=", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateLessThan(Date value) {
            addCriterion("OPERDATE <", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateLessThanOrEqualTo(Date value) {
            addCriterion("OPERDATE <=", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateIn(List<Date> values) {
            addCriterion("OPERDATE in", values, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateNotIn(List<Date> values) {
            addCriterion("OPERDATE not in", values, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateBetween(Date value1, Date value2) {
            addCriterion("OPERDATE between", value1, value2, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateNotBetween(Date value1, Date value2) {
            addCriterion("OPERDATE not between", value1, value2, "operdate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_PUNISHNOTICEINFO
     *
     * @mbggenerated do_not_delete_during_merge Tue Dec 20 16:48:18 CST 2011
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_PUNISHNOTICEINFO
     *
     * @mbggenerated Tue Dec 20 16:48:18 CST 2011
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}