package fis.repository.fs.model;

import java.util.Date;

public class FsBaseBillinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_BASE_BILLINFO.PKID
     *
     * @mbggenerated Wed Dec 21 10:11:04 CST 2011
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_BASE_BILLINFO.BILLCODE
     *
     * @mbggenerated Wed Dec 21 10:11:04 CST 2011
     */
    private String billcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_BASE_BILLINFO.BILLNAME
     *
     * @mbggenerated Wed Dec 21 10:11:04 CST 2011
     */
    private String billname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_BASE_BILLINFO.ITEMID
     *
     * @mbggenerated Wed Dec 21 10:11:04 CST 2011
     */
    private String itemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_BASE_BILLINFO.VERSION
     *
     * @mbggenerated Wed Dec 21 10:11:04 CST 2011
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_BASE_BILLINFO.OPERID
     *
     * @mbggenerated Wed Dec 21 10:11:04 CST 2011
     */
    private String operid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_BASE_BILLINFO.OPERDATE
     *
     * @mbggenerated Wed Dec 21 10:11:04 CST 2011
     */
    private Date operdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_BASE_BILLINFO.AREACODE
     *
     * @mbggenerated Wed Dec 21 10:11:04 CST 2011
     */
    private String areacode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_BASE_BILLINFO.PKID
     *
     * @return the value of FIS.FS_BASE_BILLINFO.PKID
     *
     * @mbggenerated Wed Dec 21 10:11:04 CST 2011
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_BASE_BILLINFO.PKID
     *
     * @param pkid the value for FIS.FS_BASE_BILLINFO.PKID
     *
     * @mbggenerated Wed Dec 21 10:11:04 CST 2011
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_BASE_BILLINFO.BILLCODE
     *
     * @return the value of FIS.FS_BASE_BILLINFO.BILLCODE
     *
     * @mbggenerated Wed Dec 21 10:11:04 CST 2011
     */
    public String getBillcode() {
        return billcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_BASE_BILLINFO.BILLCODE
     *
     * @param billcode the value for FIS.FS_BASE_BILLINFO.BILLCODE
     *
     * @mbggenerated Wed Dec 21 10:11:04 CST 2011
     */
    public void setBillcode(String billcode) {
        this.billcode = billcode == null ? null : billcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_BASE_BILLINFO.BILLNAME
     *
     * @return the value of FIS.FS_BASE_BILLINFO.BILLNAME
     *
     * @mbggenerated Wed Dec 21 10:11:04 CST 2011
     */
    public String getBillname() {
        return billname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_BASE_BILLINFO.BILLNAME
     *
     * @param billname the value for FIS.FS_BASE_BILLINFO.BILLNAME
     *
     * @mbggenerated Wed Dec 21 10:11:04 CST 2011
     */
    public void setBillname(String billname) {
        this.billname = billname == null ? null : billname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_BASE_BILLINFO.ITEMID
     *
     * @return the value of FIS.FS_BASE_BILLINFO.ITEMID
     *
     * @mbggenerated Wed Dec 21 10:11:04 CST 2011
     */
    public String getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_BASE_BILLINFO.ITEMID
     *
     * @param itemid the value for FIS.FS_BASE_BILLINFO.ITEMID
     *
     * @mbggenerated Wed Dec 21 10:11:04 CST 2011
     */
    public void setItemid(String itemid) {
        this.itemid = itemid == null ? null : itemid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_BASE_BILLINFO.VERSION
     *
     * @return the value of FIS.FS_BASE_BILLINFO.VERSION
     *
     * @mbggenerated Wed Dec 21 10:11:04 CST 2011
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_BASE_BILLINFO.VERSION
     *
     * @param version the value for FIS.FS_BASE_BILLINFO.VERSION
     *
     * @mbggenerated Wed Dec 21 10:11:04 CST 2011
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_BASE_BILLINFO.OPERID
     *
     * @return the value of FIS.FS_BASE_BILLINFO.OPERID
     *
     * @mbggenerated Wed Dec 21 10:11:04 CST 2011
     */
    public String getOperid() {
        return operid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_BASE_BILLINFO.OPERID
     *
     * @param operid the value for FIS.FS_BASE_BILLINFO.OPERID
     *
     * @mbggenerated Wed Dec 21 10:11:04 CST 2011
     */
    public void setOperid(String operid) {
        this.operid = operid == null ? null : operid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_BASE_BILLINFO.OPERDATE
     *
     * @return the value of FIS.FS_BASE_BILLINFO.OPERDATE
     *
     * @mbggenerated Wed Dec 21 10:11:04 CST 2011
     */
    public Date getOperdate() {
        return operdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_BASE_BILLINFO.OPERDATE
     *
     * @param operdate the value for FIS.FS_BASE_BILLINFO.OPERDATE
     *
     * @mbggenerated Wed Dec 21 10:11:04 CST 2011
     */
    public void setOperdate(Date operdate) {
        this.operdate = operdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_BASE_BILLINFO.AREACODE
     *
     * @return the value of FIS.FS_BASE_BILLINFO.AREACODE
     *
     * @mbggenerated Wed Dec 21 10:11:04 CST 2011
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_BASE_BILLINFO.AREACODE
     *
     * @param areacode the value for FIS.FS_BASE_BILLINFO.AREACODE
     *
     * @mbggenerated Wed Dec 21 10:11:04 CST 2011
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode == null ? null : areacode.trim();
    }
}