package fis.repository.fs.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FsRefundinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_REFUNDINFO
     *
     * @mbggenerated Sun Dec 25 19:14:57 CST 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_REFUNDINFO
     *
     * @mbggenerated Sun Dec 25 19:14:57 CST 2011
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_REFUNDINFO
     *
     * @mbggenerated Sun Dec 25 19:14:57 CST 2011
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_REFUNDINFO
     *
     * @mbggenerated Sun Dec 25 19:14:57 CST 2011
     */
    public FsRefundinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_REFUNDINFO
     *
     * @mbggenerated Sun Dec 25 19:14:57 CST 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_REFUNDINFO
     *
     * @mbggenerated Sun Dec 25 19:14:57 CST 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_REFUNDINFO
     *
     * @mbggenerated Sun Dec 25 19:14:57 CST 2011
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_REFUNDINFO
     *
     * @mbggenerated Sun Dec 25 19:14:57 CST 2011
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_REFUNDINFO
     *
     * @mbggenerated Sun Dec 25 19:14:57 CST 2011
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_REFUNDINFO
     *
     * @mbggenerated Sun Dec 25 19:14:57 CST 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_REFUNDINFO
     *
     * @mbggenerated Sun Dec 25 19:14:57 CST 2011
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_REFUNDINFO
     *
     * @mbggenerated Sun Dec 25 19:14:57 CST 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_REFUNDINFO
     *
     * @mbggenerated Sun Dec 25 19:14:57 CST 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_REFUNDINFO
     *
     * @mbggenerated Sun Dec 25 19:14:57 CST 2011
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_REFUNDINFO
     *
     * @mbggenerated Sun Dec 25 19:14:57 CST 2011
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andBillidIsNull() {
            addCriterion("BILLID is null");
            return (Criteria) this;
        }

        public Criteria andBillidIsNotNull() {
            addCriterion("BILLID is not null");
            return (Criteria) this;
        }

        public Criteria andBillidEqualTo(Integer value) {
            addCriterion("BILLID =", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidNotEqualTo(Integer value) {
            addCriterion("BILLID <>", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidGreaterThan(Integer value) {
            addCriterion("BILLID >", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidGreaterThanOrEqualTo(Integer value) {
            addCriterion("BILLID >=", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidLessThan(Integer value) {
            addCriterion("BILLID <", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidLessThanOrEqualTo(Integer value) {
            addCriterion("BILLID <=", value, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidIn(List<Integer> values) {
            addCriterion("BILLID in", values, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidNotIn(List<Integer> values) {
            addCriterion("BILLID not in", values, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidBetween(Integer value1, Integer value2) {
            addCriterion("BILLID between", value1, value2, "billid");
            return (Criteria) this;
        }

        public Criteria andBillidNotBetween(Integer value1, Integer value2) {
            addCriterion("BILLID not between", value1, value2, "billid");
            return (Criteria) this;
        }

        public Criteria andRefundapplycodeIsNull() {
            addCriterion("REFUNDAPPLYCODE is null");
            return (Criteria) this;
        }

        public Criteria andRefundapplycodeIsNotNull() {
            addCriterion("REFUNDAPPLYCODE is not null");
            return (Criteria) this;
        }

        public Criteria andRefundapplycodeEqualTo(String value) {
            addCriterion("REFUNDAPPLYCODE =", value, "refundapplycode");
            return (Criteria) this;
        }

        public Criteria andRefundapplycodeNotEqualTo(String value) {
            addCriterion("REFUNDAPPLYCODE <>", value, "refundapplycode");
            return (Criteria) this;
        }

        public Criteria andRefundapplycodeGreaterThan(String value) {
            addCriterion("REFUNDAPPLYCODE >", value, "refundapplycode");
            return (Criteria) this;
        }

        public Criteria andRefundapplycodeGreaterThanOrEqualTo(String value) {
            addCriterion("REFUNDAPPLYCODE >=", value, "refundapplycode");
            return (Criteria) this;
        }

        public Criteria andRefundapplycodeLessThan(String value) {
            addCriterion("REFUNDAPPLYCODE <", value, "refundapplycode");
            return (Criteria) this;
        }

        public Criteria andRefundapplycodeLessThanOrEqualTo(String value) {
            addCriterion("REFUNDAPPLYCODE <=", value, "refundapplycode");
            return (Criteria) this;
        }

        public Criteria andRefundapplycodeLike(String value) {
            addCriterion("REFUNDAPPLYCODE like", value, "refundapplycode");
            return (Criteria) this;
        }

        public Criteria andRefundapplycodeNotLike(String value) {
            addCriterion("REFUNDAPPLYCODE not like", value, "refundapplycode");
            return (Criteria) this;
        }

        public Criteria andRefundapplycodeIn(List<String> values) {
            addCriterion("REFUNDAPPLYCODE in", values, "refundapplycode");
            return (Criteria) this;
        }

        public Criteria andRefundapplycodeNotIn(List<String> values) {
            addCriterion("REFUNDAPPLYCODE not in", values, "refundapplycode");
            return (Criteria) this;
        }

        public Criteria andRefundapplycodeBetween(String value1, String value2) {
            addCriterion("REFUNDAPPLYCODE between", value1, value2, "refundapplycode");
            return (Criteria) this;
        }

        public Criteria andRefundapplycodeNotBetween(String value1, String value2) {
            addCriterion("REFUNDAPPLYCODE not between", value1, value2, "refundapplycode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeIsNull() {
            addCriterion("PAYNOTESCODE is null");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeIsNotNull() {
            addCriterion("PAYNOTESCODE is not null");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeEqualTo(String value) {
            addCriterion("PAYNOTESCODE =", value, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeNotEqualTo(String value) {
            addCriterion("PAYNOTESCODE <>", value, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeGreaterThan(String value) {
            addCriterion("PAYNOTESCODE >", value, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeGreaterThanOrEqualTo(String value) {
            addCriterion("PAYNOTESCODE >=", value, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeLessThan(String value) {
            addCriterion("PAYNOTESCODE <", value, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeLessThanOrEqualTo(String value) {
            addCriterion("PAYNOTESCODE <=", value, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeLike(String value) {
            addCriterion("PAYNOTESCODE like", value, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeNotLike(String value) {
            addCriterion("PAYNOTESCODE not like", value, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeIn(List<String> values) {
            addCriterion("PAYNOTESCODE in", values, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeNotIn(List<String> values) {
            addCriterion("PAYNOTESCODE not in", values, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeBetween(String value1, String value2) {
            addCriterion("PAYNOTESCODE between", value1, value2, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPaynotescodeNotBetween(String value1, String value2) {
            addCriterion("PAYNOTESCODE not between", value1, value2, "paynotescode");
            return (Criteria) this;
        }

        public Criteria andPerformdeptIsNull() {
            addCriterion("PERFORMDEPT is null");
            return (Criteria) this;
        }

        public Criteria andPerformdeptIsNotNull() {
            addCriterion("PERFORMDEPT is not null");
            return (Criteria) this;
        }

        public Criteria andPerformdeptEqualTo(Integer value) {
            addCriterion("PERFORMDEPT =", value, "performdept");
            return (Criteria) this;
        }

        public Criteria andPerformdeptNotEqualTo(Integer value) {
            addCriterion("PERFORMDEPT <>", value, "performdept");
            return (Criteria) this;
        }

        public Criteria andPerformdeptGreaterThan(Integer value) {
            addCriterion("PERFORMDEPT >", value, "performdept");
            return (Criteria) this;
        }

        public Criteria andPerformdeptGreaterThanOrEqualTo(Integer value) {
            addCriterion("PERFORMDEPT >=", value, "performdept");
            return (Criteria) this;
        }

        public Criteria andPerformdeptLessThan(Integer value) {
            addCriterion("PERFORMDEPT <", value, "performdept");
            return (Criteria) this;
        }

        public Criteria andPerformdeptLessThanOrEqualTo(Integer value) {
            addCriterion("PERFORMDEPT <=", value, "performdept");
            return (Criteria) this;
        }

        public Criteria andPerformdeptIn(List<Integer> values) {
            addCriterion("PERFORMDEPT in", values, "performdept");
            return (Criteria) this;
        }

        public Criteria andPerformdeptNotIn(List<Integer> values) {
            addCriterion("PERFORMDEPT not in", values, "performdept");
            return (Criteria) this;
        }

        public Criteria andPerformdeptBetween(Integer value1, Integer value2) {
            addCriterion("PERFORMDEPT between", value1, value2, "performdept");
            return (Criteria) this;
        }

        public Criteria andPerformdeptNotBetween(Integer value1, Integer value2) {
            addCriterion("PERFORMDEPT not between", value1, value2, "performdept");
            return (Criteria) this;
        }

        public Criteria andCreateuserIsNull() {
            addCriterion("CREATEUSER is null");
            return (Criteria) this;
        }

        public Criteria andCreateuserIsNotNull() {
            addCriterion("CREATEUSER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateuserEqualTo(String value) {
            addCriterion("CREATEUSER =", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotEqualTo(String value) {
            addCriterion("CREATEUSER <>", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserGreaterThan(String value) {
            addCriterion("CREATEUSER >", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEUSER >=", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLessThan(String value) {
            addCriterion("CREATEUSER <", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLessThanOrEqualTo(String value) {
            addCriterion("CREATEUSER <=", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLike(String value) {
            addCriterion("CREATEUSER like", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotLike(String value) {
            addCriterion("CREATEUSER not like", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserIn(List<String> values) {
            addCriterion("CREATEUSER in", values, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotIn(List<String> values) {
            addCriterion("CREATEUSER not in", values, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserBetween(String value1, String value2) {
            addCriterion("CREATEUSER between", value1, value2, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotBetween(String value1, String value2) {
            addCriterion("CREATEUSER not between", value1, value2, "createuser");
            return (Criteria) this;
        }

        public Criteria andRecusernameIsNull() {
            addCriterion("RECUSERNAME is null");
            return (Criteria) this;
        }

        public Criteria andRecusernameIsNotNull() {
            addCriterion("RECUSERNAME is not null");
            return (Criteria) this;
        }

        public Criteria andRecusernameEqualTo(String value) {
            addCriterion("RECUSERNAME =", value, "recusername");
            return (Criteria) this;
        }

        public Criteria andRecusernameNotEqualTo(String value) {
            addCriterion("RECUSERNAME <>", value, "recusername");
            return (Criteria) this;
        }

        public Criteria andRecusernameGreaterThan(String value) {
            addCriterion("RECUSERNAME >", value, "recusername");
            return (Criteria) this;
        }

        public Criteria andRecusernameGreaterThanOrEqualTo(String value) {
            addCriterion("RECUSERNAME >=", value, "recusername");
            return (Criteria) this;
        }

        public Criteria andRecusernameLessThan(String value) {
            addCriterion("RECUSERNAME <", value, "recusername");
            return (Criteria) this;
        }

        public Criteria andRecusernameLessThanOrEqualTo(String value) {
            addCriterion("RECUSERNAME <=", value, "recusername");
            return (Criteria) this;
        }

        public Criteria andRecusernameLike(String value) {
            addCriterion("RECUSERNAME like", value, "recusername");
            return (Criteria) this;
        }

        public Criteria andRecusernameNotLike(String value) {
            addCriterion("RECUSERNAME not like", value, "recusername");
            return (Criteria) this;
        }

        public Criteria andRecusernameIn(List<String> values) {
            addCriterion("RECUSERNAME in", values, "recusername");
            return (Criteria) this;
        }

        public Criteria andRecusernameNotIn(List<String> values) {
            addCriterion("RECUSERNAME not in", values, "recusername");
            return (Criteria) this;
        }

        public Criteria andRecusernameBetween(String value1, String value2) {
            addCriterion("RECUSERNAME between", value1, value2, "recusername");
            return (Criteria) this;
        }

        public Criteria andRecusernameNotBetween(String value1, String value2) {
            addCriterion("RECUSERNAME not between", value1, value2, "recusername");
            return (Criteria) this;
        }

        public Criteria andRecuserbankIsNull() {
            addCriterion("RECUSERBANK is null");
            return (Criteria) this;
        }

        public Criteria andRecuserbankIsNotNull() {
            addCriterion("RECUSERBANK is not null");
            return (Criteria) this;
        }

        public Criteria andRecuserbankEqualTo(String value) {
            addCriterion("RECUSERBANK =", value, "recuserbank");
            return (Criteria) this;
        }

        public Criteria andRecuserbankNotEqualTo(String value) {
            addCriterion("RECUSERBANK <>", value, "recuserbank");
            return (Criteria) this;
        }

        public Criteria andRecuserbankGreaterThan(String value) {
            addCriterion("RECUSERBANK >", value, "recuserbank");
            return (Criteria) this;
        }

        public Criteria andRecuserbankGreaterThanOrEqualTo(String value) {
            addCriterion("RECUSERBANK >=", value, "recuserbank");
            return (Criteria) this;
        }

        public Criteria andRecuserbankLessThan(String value) {
            addCriterion("RECUSERBANK <", value, "recuserbank");
            return (Criteria) this;
        }

        public Criteria andRecuserbankLessThanOrEqualTo(String value) {
            addCriterion("RECUSERBANK <=", value, "recuserbank");
            return (Criteria) this;
        }

        public Criteria andRecuserbankLike(String value) {
            addCriterion("RECUSERBANK like", value, "recuserbank");
            return (Criteria) this;
        }

        public Criteria andRecuserbankNotLike(String value) {
            addCriterion("RECUSERBANK not like", value, "recuserbank");
            return (Criteria) this;
        }

        public Criteria andRecuserbankIn(List<String> values) {
            addCriterion("RECUSERBANK in", values, "recuserbank");
            return (Criteria) this;
        }

        public Criteria andRecuserbankNotIn(List<String> values) {
            addCriterion("RECUSERBANK not in", values, "recuserbank");
            return (Criteria) this;
        }

        public Criteria andRecuserbankBetween(String value1, String value2) {
            addCriterion("RECUSERBANK between", value1, value2, "recuserbank");
            return (Criteria) this;
        }

        public Criteria andRecuserbankNotBetween(String value1, String value2) {
            addCriterion("RECUSERBANK not between", value1, value2, "recuserbank");
            return (Criteria) this;
        }

        public Criteria andRecuserbankaccountIsNull() {
            addCriterion("RECUSERBANKACCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andRecuserbankaccountIsNotNull() {
            addCriterion("RECUSERBANKACCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andRecuserbankaccountEqualTo(String value) {
            addCriterion("RECUSERBANKACCOUNT =", value, "recuserbankaccount");
            return (Criteria) this;
        }

        public Criteria andRecuserbankaccountNotEqualTo(String value) {
            addCriterion("RECUSERBANKACCOUNT <>", value, "recuserbankaccount");
            return (Criteria) this;
        }

        public Criteria andRecuserbankaccountGreaterThan(String value) {
            addCriterion("RECUSERBANKACCOUNT >", value, "recuserbankaccount");
            return (Criteria) this;
        }

        public Criteria andRecuserbankaccountGreaterThanOrEqualTo(String value) {
            addCriterion("RECUSERBANKACCOUNT >=", value, "recuserbankaccount");
            return (Criteria) this;
        }

        public Criteria andRecuserbankaccountLessThan(String value) {
            addCriterion("RECUSERBANKACCOUNT <", value, "recuserbankaccount");
            return (Criteria) this;
        }

        public Criteria andRecuserbankaccountLessThanOrEqualTo(String value) {
            addCriterion("RECUSERBANKACCOUNT <=", value, "recuserbankaccount");
            return (Criteria) this;
        }

        public Criteria andRecuserbankaccountLike(String value) {
            addCriterion("RECUSERBANKACCOUNT like", value, "recuserbankaccount");
            return (Criteria) this;
        }

        public Criteria andRecuserbankaccountNotLike(String value) {
            addCriterion("RECUSERBANKACCOUNT not like", value, "recuserbankaccount");
            return (Criteria) this;
        }

        public Criteria andRecuserbankaccountIn(List<String> values) {
            addCriterion("RECUSERBANKACCOUNT in", values, "recuserbankaccount");
            return (Criteria) this;
        }

        public Criteria andRecuserbankaccountNotIn(List<String> values) {
            addCriterion("RECUSERBANKACCOUNT not in", values, "recuserbankaccount");
            return (Criteria) this;
        }

        public Criteria andRecuserbankaccountBetween(String value1, String value2) {
            addCriterion("RECUSERBANKACCOUNT between", value1, value2, "recuserbankaccount");
            return (Criteria) this;
        }

        public Criteria andRecuserbankaccountNotBetween(String value1, String value2) {
            addCriterion("RECUSERBANKACCOUNT not between", value1, value2, "recuserbankaccount");
            return (Criteria) this;
        }

        public Criteria andRefundreasonIsNull() {
            addCriterion("REFUNDREASON is null");
            return (Criteria) this;
        }

        public Criteria andRefundreasonIsNotNull() {
            addCriterion("REFUNDREASON is not null");
            return (Criteria) this;
        }

        public Criteria andRefundreasonEqualTo(String value) {
            addCriterion("REFUNDREASON =", value, "refundreason");
            return (Criteria) this;
        }

        public Criteria andRefundreasonNotEqualTo(String value) {
            addCriterion("REFUNDREASON <>", value, "refundreason");
            return (Criteria) this;
        }

        public Criteria andRefundreasonGreaterThan(String value) {
            addCriterion("REFUNDREASON >", value, "refundreason");
            return (Criteria) this;
        }

        public Criteria andRefundreasonGreaterThanOrEqualTo(String value) {
            addCriterion("REFUNDREASON >=", value, "refundreason");
            return (Criteria) this;
        }

        public Criteria andRefundreasonLessThan(String value) {
            addCriterion("REFUNDREASON <", value, "refundreason");
            return (Criteria) this;
        }

        public Criteria andRefundreasonLessThanOrEqualTo(String value) {
            addCriterion("REFUNDREASON <=", value, "refundreason");
            return (Criteria) this;
        }

        public Criteria andRefundreasonLike(String value) {
            addCriterion("REFUNDREASON like", value, "refundreason");
            return (Criteria) this;
        }

        public Criteria andRefundreasonNotLike(String value) {
            addCriterion("REFUNDREASON not like", value, "refundreason");
            return (Criteria) this;
        }

        public Criteria andRefundreasonIn(List<String> values) {
            addCriterion("REFUNDREASON in", values, "refundreason");
            return (Criteria) this;
        }

        public Criteria andRefundreasonNotIn(List<String> values) {
            addCriterion("REFUNDREASON not in", values, "refundreason");
            return (Criteria) this;
        }

        public Criteria andRefundreasonBetween(String value1, String value2) {
            addCriterion("REFUNDREASON between", value1, value2, "refundreason");
            return (Criteria) this;
        }

        public Criteria andRefundreasonNotBetween(String value1, String value2) {
            addCriterion("REFUNDREASON not between", value1, value2, "refundreason");
            return (Criteria) this;
        }

        public Criteria andAuditorIsNull() {
            addCriterion("AUDITOR is null");
            return (Criteria) this;
        }

        public Criteria andAuditorIsNotNull() {
            addCriterion("AUDITOR is not null");
            return (Criteria) this;
        }

        public Criteria andAuditorEqualTo(Integer value) {
            addCriterion("AUDITOR =", value, "auditor");
            return (Criteria) this;
        }

        public Criteria andAuditorNotEqualTo(Integer value) {
            addCriterion("AUDITOR <>", value, "auditor");
            return (Criteria) this;
        }

        public Criteria andAuditorGreaterThan(Integer value) {
            addCriterion("AUDITOR >", value, "auditor");
            return (Criteria) this;
        }

        public Criteria andAuditorGreaterThanOrEqualTo(Integer value) {
            addCriterion("AUDITOR >=", value, "auditor");
            return (Criteria) this;
        }

        public Criteria andAuditorLessThan(Integer value) {
            addCriterion("AUDITOR <", value, "auditor");
            return (Criteria) this;
        }

        public Criteria andAuditorLessThanOrEqualTo(Integer value) {
            addCriterion("AUDITOR <=", value, "auditor");
            return (Criteria) this;
        }

        public Criteria andAuditorIn(List<Integer> values) {
            addCriterion("AUDITOR in", values, "auditor");
            return (Criteria) this;
        }

        public Criteria andAuditorNotIn(List<Integer> values) {
            addCriterion("AUDITOR not in", values, "auditor");
            return (Criteria) this;
        }

        public Criteria andAuditorBetween(Integer value1, Integer value2) {
            addCriterion("AUDITOR between", value1, value2, "auditor");
            return (Criteria) this;
        }

        public Criteria andAuditorNotBetween(Integer value1, Integer value2) {
            addCriterion("AUDITOR not between", value1, value2, "auditor");
            return (Criteria) this;
        }

        public Criteria andAuditamtIsNull() {
            addCriterion("AUDITAMT is null");
            return (Criteria) this;
        }

        public Criteria andAuditamtIsNotNull() {
            addCriterion("AUDITAMT is not null");
            return (Criteria) this;
        }

        public Criteria andAuditamtEqualTo(BigDecimal value) {
            addCriterion("AUDITAMT =", value, "auditamt");
            return (Criteria) this;
        }

        public Criteria andAuditamtNotEqualTo(BigDecimal value) {
            addCriterion("AUDITAMT <>", value, "auditamt");
            return (Criteria) this;
        }

        public Criteria andAuditamtGreaterThan(BigDecimal value) {
            addCriterion("AUDITAMT >", value, "auditamt");
            return (Criteria) this;
        }

        public Criteria andAuditamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AUDITAMT >=", value, "auditamt");
            return (Criteria) this;
        }

        public Criteria andAuditamtLessThan(BigDecimal value) {
            addCriterion("AUDITAMT <", value, "auditamt");
            return (Criteria) this;
        }

        public Criteria andAuditamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AUDITAMT <=", value, "auditamt");
            return (Criteria) this;
        }

        public Criteria andAuditamtIn(List<BigDecimal> values) {
            addCriterion("AUDITAMT in", values, "auditamt");
            return (Criteria) this;
        }

        public Criteria andAuditamtNotIn(List<BigDecimal> values) {
            addCriterion("AUDITAMT not in", values, "auditamt");
            return (Criteria) this;
        }

        public Criteria andAuditamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AUDITAMT between", value1, value2, "auditamt");
            return (Criteria) this;
        }

        public Criteria andAuditamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AUDITAMT not between", value1, value2, "auditamt");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("CREATETIME is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("CREATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(String value) {
            addCriterion("CREATETIME =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(String value) {
            addCriterion("CREATETIME <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(String value) {
            addCriterion("CREATETIME >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATETIME >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(String value) {
            addCriterion("CREATETIME <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(String value) {
            addCriterion("CREATETIME <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLike(String value) {
            addCriterion("CREATETIME like", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotLike(String value) {
            addCriterion("CREATETIME not like", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<String> values) {
            addCriterion("CREATETIME in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<String> values) {
            addCriterion("CREATETIME not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(String value1, String value2) {
            addCriterion("CREATETIME between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(String value1, String value2) {
            addCriterion("CREATETIME not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andTotalamtIsNull() {
            addCriterion("TOTALAMT is null");
            return (Criteria) this;
        }

        public Criteria andTotalamtIsNotNull() {
            addCriterion("TOTALAMT is not null");
            return (Criteria) this;
        }

        public Criteria andTotalamtEqualTo(BigDecimal value) {
            addCriterion("TOTALAMT =", value, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtNotEqualTo(BigDecimal value) {
            addCriterion("TOTALAMT <>", value, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtGreaterThan(BigDecimal value) {
            addCriterion("TOTALAMT >", value, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTALAMT >=", value, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtLessThan(BigDecimal value) {
            addCriterion("TOTALAMT <", value, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTALAMT <=", value, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtIn(List<BigDecimal> values) {
            addCriterion("TOTALAMT in", values, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtNotIn(List<BigDecimal> values) {
            addCriterion("TOTALAMT not in", values, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTALAMT between", value1, value2, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTALAMT not between", value1, value2, "totalamt");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNull() {
            addCriterion("CREATER is null");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNotNull() {
            addCriterion("CREATER is not null");
            return (Criteria) this;
        }

        public Criteria andCreaterEqualTo(Integer value) {
            addCriterion("CREATER =", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotEqualTo(Integer value) {
            addCriterion("CREATER <>", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThan(Integer value) {
            addCriterion("CREATER >", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThanOrEqualTo(Integer value) {
            addCriterion("CREATER >=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThan(Integer value) {
            addCriterion("CREATER <", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThanOrEqualTo(Integer value) {
            addCriterion("CREATER <=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterIn(List<Integer> values) {
            addCriterion("CREATER in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotIn(List<Integer> values) {
            addCriterion("CREATER not in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterBetween(Integer value1, Integer value2) {
            addCriterion("CREATER between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotBetween(Integer value1, Integer value2) {
            addCriterion("CREATER not between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andAgentbankIsNull() {
            addCriterion("AGENTBANK is null");
            return (Criteria) this;
        }

        public Criteria andAgentbankIsNotNull() {
            addCriterion("AGENTBANK is not null");
            return (Criteria) this;
        }

        public Criteria andAgentbankEqualTo(Integer value) {
            addCriterion("AGENTBANK =", value, "agentbank");
            return (Criteria) this;
        }

        public Criteria andAgentbankNotEqualTo(Integer value) {
            addCriterion("AGENTBANK <>", value, "agentbank");
            return (Criteria) this;
        }

        public Criteria andAgentbankGreaterThan(Integer value) {
            addCriterion("AGENTBANK >", value, "agentbank");
            return (Criteria) this;
        }

        public Criteria andAgentbankGreaterThanOrEqualTo(Integer value) {
            addCriterion("AGENTBANK >=", value, "agentbank");
            return (Criteria) this;
        }

        public Criteria andAgentbankLessThan(Integer value) {
            addCriterion("AGENTBANK <", value, "agentbank");
            return (Criteria) this;
        }

        public Criteria andAgentbankLessThanOrEqualTo(Integer value) {
            addCriterion("AGENTBANK <=", value, "agentbank");
            return (Criteria) this;
        }

        public Criteria andAgentbankIn(List<Integer> values) {
            addCriterion("AGENTBANK in", values, "agentbank");
            return (Criteria) this;
        }

        public Criteria andAgentbankNotIn(List<Integer> values) {
            addCriterion("AGENTBANK not in", values, "agentbank");
            return (Criteria) this;
        }

        public Criteria andAgentbankBetween(Integer value1, Integer value2) {
            addCriterion("AGENTBANK between", value1, value2, "agentbank");
            return (Criteria) this;
        }

        public Criteria andAgentbankNotBetween(Integer value1, Integer value2) {
            addCriterion("AGENTBANK not between", value1, value2, "agentbank");
            return (Criteria) this;
        }

        public Criteria andPrinttagIsNull() {
            addCriterion("PRINTTAG is null");
            return (Criteria) this;
        }

        public Criteria andPrinttagIsNotNull() {
            addCriterion("PRINTTAG is not null");
            return (Criteria) this;
        }

        public Criteria andPrinttagEqualTo(Integer value) {
            addCriterion("PRINTTAG =", value, "printtag");
            return (Criteria) this;
        }

        public Criteria andPrinttagNotEqualTo(Integer value) {
            addCriterion("PRINTTAG <>", value, "printtag");
            return (Criteria) this;
        }

        public Criteria andPrinttagGreaterThan(Integer value) {
            addCriterion("PRINTTAG >", value, "printtag");
            return (Criteria) this;
        }

        public Criteria andPrinttagGreaterThanOrEqualTo(Integer value) {
            addCriterion("PRINTTAG >=", value, "printtag");
            return (Criteria) this;
        }

        public Criteria andPrinttagLessThan(Integer value) {
            addCriterion("PRINTTAG <", value, "printtag");
            return (Criteria) this;
        }

        public Criteria andPrinttagLessThanOrEqualTo(Integer value) {
            addCriterion("PRINTTAG <=", value, "printtag");
            return (Criteria) this;
        }

        public Criteria andPrinttagIn(List<Integer> values) {
            addCriterion("PRINTTAG in", values, "printtag");
            return (Criteria) this;
        }

        public Criteria andPrinttagNotIn(List<Integer> values) {
            addCriterion("PRINTTAG not in", values, "printtag");
            return (Criteria) this;
        }

        public Criteria andPrinttagBetween(Integer value1, Integer value2) {
            addCriterion("PRINTTAG between", value1, value2, "printtag");
            return (Criteria) this;
        }

        public Criteria andPrinttagNotBetween(Integer value1, Integer value2) {
            addCriterion("PRINTTAG not between", value1, value2, "printtag");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("VERSION is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("VERSION =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("VERSION <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("VERSION >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("VERSION >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("VERSION <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("VERSION <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("VERSION in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("VERSION not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("VERSION between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("VERSION not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("CREATED_BY is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("CREATED_BY is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("CREATED_BY =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("CREATED_BY <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("CREATED_BY >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("CREATED_BY >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("CREATED_BY <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("CREATED_BY <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("CREATED_BY like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("CREATED_BY not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("CREATED_BY in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("CREATED_BY not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("CREATED_BY between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("CREATED_BY not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedDtIsNull() {
            addCriterion("CREATED_DT is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDtIsNotNull() {
            addCriterion("CREATED_DT is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDtEqualTo(Date value) {
            addCriterion("CREATED_DT =", value, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtNotEqualTo(Date value) {
            addCriterion("CREATED_DT <>", value, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtGreaterThan(Date value) {
            addCriterion("CREATED_DT >", value, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATED_DT >=", value, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtLessThan(Date value) {
            addCriterion("CREATED_DT <", value, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtLessThanOrEqualTo(Date value) {
            addCriterion("CREATED_DT <=", value, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtIn(List<Date> values) {
            addCriterion("CREATED_DT in", values, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtNotIn(List<Date> values) {
            addCriterion("CREATED_DT not in", values, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtBetween(Date value1, Date value2) {
            addCriterion("CREATED_DT between", value1, value2, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtNotBetween(Date value1, Date value2) {
            addCriterion("CREATED_DT not between", value1, value2, "createdDt");
            return (Criteria) this;
        }

        public Criteria andLastUpdByIsNull() {
            addCriterion("LAST_UPD_BY is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdByIsNotNull() {
            addCriterion("LAST_UPD_BY is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdByEqualTo(String value) {
            addCriterion("LAST_UPD_BY =", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByNotEqualTo(String value) {
            addCriterion("LAST_UPD_BY <>", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByGreaterThan(String value) {
            addCriterion("LAST_UPD_BY >", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_UPD_BY >=", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByLessThan(String value) {
            addCriterion("LAST_UPD_BY <", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByLessThanOrEqualTo(String value) {
            addCriterion("LAST_UPD_BY <=", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByLike(String value) {
            addCriterion("LAST_UPD_BY like", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByNotLike(String value) {
            addCriterion("LAST_UPD_BY not like", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByIn(List<String> values) {
            addCriterion("LAST_UPD_BY in", values, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByNotIn(List<String> values) {
            addCriterion("LAST_UPD_BY not in", values, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByBetween(String value1, String value2) {
            addCriterion("LAST_UPD_BY between", value1, value2, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByNotBetween(String value1, String value2) {
            addCriterion("LAST_UPD_BY not between", value1, value2, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateIsNull() {
            addCriterion("LAST_UPD_DATE is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateIsNotNull() {
            addCriterion("LAST_UPD_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateEqualTo(Date value) {
            addCriterion("LAST_UPD_DATE =", value, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateNotEqualTo(Date value) {
            addCriterion("LAST_UPD_DATE <>", value, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateGreaterThan(Date value) {
            addCriterion("LAST_UPD_DATE >", value, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_UPD_DATE >=", value, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateLessThan(Date value) {
            addCriterion("LAST_UPD_DATE <", value, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateLessThanOrEqualTo(Date value) {
            addCriterion("LAST_UPD_DATE <=", value, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateIn(List<Date> values) {
            addCriterion("LAST_UPD_DATE in", values, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateNotIn(List<Date> values) {
            addCriterion("LAST_UPD_DATE not in", values, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateBetween(Date value1, Date value2) {
            addCriterion("LAST_UPD_DATE between", value1, value2, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateNotBetween(Date value1, Date value2) {
            addCriterion("LAST_UPD_DATE not between", value1, value2, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andAreacodeIsNull() {
            addCriterion("AREACODE is null");
            return (Criteria) this;
        }

        public Criteria andAreacodeIsNotNull() {
            addCriterion("AREACODE is not null");
            return (Criteria) this;
        }

        public Criteria andAreacodeEqualTo(String value) {
            addCriterion("AREACODE =", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeNotEqualTo(String value) {
            addCriterion("AREACODE <>", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeGreaterThan(String value) {
            addCriterion("AREACODE >", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeGreaterThanOrEqualTo(String value) {
            addCriterion("AREACODE >=", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeLessThan(String value) {
            addCriterion("AREACODE <", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeLessThanOrEqualTo(String value) {
            addCriterion("AREACODE <=", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeLike(String value) {
            addCriterion("AREACODE like", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeNotLike(String value) {
            addCriterion("AREACODE not like", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeIn(List<String> values) {
            addCriterion("AREACODE in", values, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeNotIn(List<String> values) {
            addCriterion("AREACODE not in", values, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeBetween(String value1, String value2) {
            addCriterion("AREACODE between", value1, value2, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeNotBetween(String value1, String value2) {
            addCriterion("AREACODE not between", value1, value2, "areacode");
            return (Criteria) this;
        }

        public Criteria andProcessstatusIsNull() {
            addCriterion("PROCESSSTATUS is null");
            return (Criteria) this;
        }

        public Criteria andProcessstatusIsNotNull() {
            addCriterion("PROCESSSTATUS is not null");
            return (Criteria) this;
        }

        public Criteria andProcessstatusEqualTo(String value) {
            addCriterion("PROCESSSTATUS =", value, "processstatus");
            return (Criteria) this;
        }

        public Criteria andProcessstatusNotEqualTo(String value) {
            addCriterion("PROCESSSTATUS <>", value, "processstatus");
            return (Criteria) this;
        }

        public Criteria andProcessstatusGreaterThan(String value) {
            addCriterion("PROCESSSTATUS >", value, "processstatus");
            return (Criteria) this;
        }

        public Criteria andProcessstatusGreaterThanOrEqualTo(String value) {
            addCriterion("PROCESSSTATUS >=", value, "processstatus");
            return (Criteria) this;
        }

        public Criteria andProcessstatusLessThan(String value) {
            addCriterion("PROCESSSTATUS <", value, "processstatus");
            return (Criteria) this;
        }

        public Criteria andProcessstatusLessThanOrEqualTo(String value) {
            addCriterion("PROCESSSTATUS <=", value, "processstatus");
            return (Criteria) this;
        }

        public Criteria andProcessstatusLike(String value) {
            addCriterion("PROCESSSTATUS like", value, "processstatus");
            return (Criteria) this;
        }

        public Criteria andProcessstatusNotLike(String value) {
            addCriterion("PROCESSSTATUS not like", value, "processstatus");
            return (Criteria) this;
        }

        public Criteria andProcessstatusIn(List<String> values) {
            addCriterion("PROCESSSTATUS in", values, "processstatus");
            return (Criteria) this;
        }

        public Criteria andProcessstatusNotIn(List<String> values) {
            addCriterion("PROCESSSTATUS not in", values, "processstatus");
            return (Criteria) this;
        }

        public Criteria andProcessstatusBetween(String value1, String value2) {
            addCriterion("PROCESSSTATUS between", value1, value2, "processstatus");
            return (Criteria) this;
        }

        public Criteria andProcessstatusNotBetween(String value1, String value2) {
            addCriterion("PROCESSSTATUS not between", value1, value2, "processstatus");
            return (Criteria) this;
        }

        public Criteria andPrfrmdeptnameIsNull() {
            addCriterion("PRFRMDEPTNAME is null");
            return (Criteria) this;
        }

        public Criteria andPrfrmdeptnameIsNotNull() {
            addCriterion("PRFRMDEPTNAME is not null");
            return (Criteria) this;
        }

        public Criteria andPrfrmdeptnameEqualTo(String value) {
            addCriterion("PRFRMDEPTNAME =", value, "prfrmdeptname");
            return (Criteria) this;
        }

        public Criteria andPrfrmdeptnameNotEqualTo(String value) {
            addCriterion("PRFRMDEPTNAME <>", value, "prfrmdeptname");
            return (Criteria) this;
        }

        public Criteria andPrfrmdeptnameGreaterThan(String value) {
            addCriterion("PRFRMDEPTNAME >", value, "prfrmdeptname");
            return (Criteria) this;
        }

        public Criteria andPrfrmdeptnameGreaterThanOrEqualTo(String value) {
            addCriterion("PRFRMDEPTNAME >=", value, "prfrmdeptname");
            return (Criteria) this;
        }

        public Criteria andPrfrmdeptnameLessThan(String value) {
            addCriterion("PRFRMDEPTNAME <", value, "prfrmdeptname");
            return (Criteria) this;
        }

        public Criteria andPrfrmdeptnameLessThanOrEqualTo(String value) {
            addCriterion("PRFRMDEPTNAME <=", value, "prfrmdeptname");
            return (Criteria) this;
        }

        public Criteria andPrfrmdeptnameLike(String value) {
            addCriterion("PRFRMDEPTNAME like", value, "prfrmdeptname");
            return (Criteria) this;
        }

        public Criteria andPrfrmdeptnameNotLike(String value) {
            addCriterion("PRFRMDEPTNAME not like", value, "prfrmdeptname");
            return (Criteria) this;
        }

        public Criteria andPrfrmdeptnameIn(List<String> values) {
            addCriterion("PRFRMDEPTNAME in", values, "prfrmdeptname");
            return (Criteria) this;
        }

        public Criteria andPrfrmdeptnameNotIn(List<String> values) {
            addCriterion("PRFRMDEPTNAME not in", values, "prfrmdeptname");
            return (Criteria) this;
        }

        public Criteria andPrfrmdeptnameBetween(String value1, String value2) {
            addCriterion("PRFRMDEPTNAME between", value1, value2, "prfrmdeptname");
            return (Criteria) this;
        }

        public Criteria andPrfrmdeptnameNotBetween(String value1, String value2) {
            addCriterion("PRFRMDEPTNAME not between", value1, value2, "prfrmdeptname");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_REFUNDINFO
     *
     * @mbggenerated do_not_delete_during_merge Sun Dec 25 19:14:57 CST 2011
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_REFUNDINFO
     *
     * @mbggenerated Sun Dec 25 19:14:57 CST 2011
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}