package fis.repository.pay.dao;

import fis.repository.pay.model.PayActinfo;
import fis.repository.pay.model.PayActinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface PayActinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.PAY_ACTINFO
     *
     * @mbggenerated Mon Feb 06 14:27:24 CST 2012
     */
    int countByExample(PayActinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.PAY_ACTINFO
     *
     * @mbggenerated Mon Feb 06 14:27:24 CST 2012
     */
    int deleteByExample(PayActinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.PAY_ACTINFO
     *
     * @mbggenerated Mon Feb 06 14:27:24 CST 2012
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.PAY_ACTINFO
     *
     * @mbggenerated Mon Feb 06 14:27:24 CST 2012
     */
    int insert(PayActinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.PAY_ACTINFO
     *
     * @mbggenerated Mon Feb 06 14:27:24 CST 2012
     */
    int insertSelective(PayActinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.PAY_ACTINFO
     *
     * @mbggenerated Mon Feb 06 14:27:24 CST 2012
     */
    List<PayActinfo> selectByExample(PayActinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.PAY_ACTINFO
     *
     * @mbggenerated Mon Feb 06 14:27:24 CST 2012
     */
    PayActinfo selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.PAY_ACTINFO
     *
     * @mbggenerated Mon Feb 06 14:27:24 CST 2012
     */
    int updateByExampleSelective(@Param("record") PayActinfo record, @Param("example") PayActinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.PAY_ACTINFO
     *
     * @mbggenerated Mon Feb 06 14:27:24 CST 2012
     */
    int updateByExample(@Param("record") PayActinfo record, @Param("example") PayActinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.PAY_ACTINFO
     *
     * @mbggenerated Mon Feb 06 14:27:24 CST 2012
     */
    int updateByPrimaryKeySelective(PayActinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.PAY_ACTINFO
     *
     * @mbggenerated Mon Feb 06 14:27:24 CST 2012
     */
    int updateByPrimaryKey(PayActinfo record);
}