package fis.repository.qdf.dao;

import fis.repository.qdf.model.FsQdfPaymentInfo;
import fis.repository.qdf.model.FsQdfPaymentInfoExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface FsQdfPaymentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PAYMENT_INFO
     *
     * @mbggenerated Tue May 21 16:00:50 CST 2013
     */
    int countByExample(FsQdfPaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PAYMENT_INFO
     *
     * @mbggenerated Tue May 21 16:00:50 CST 2013
     */
    int deleteByExample(FsQdfPaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PAYMENT_INFO
     *
     * @mbggenerated Tue May 21 16:00:50 CST 2013
     */
    int insert(FsQdfPaymentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PAYMENT_INFO
     *
     * @mbggenerated Tue May 21 16:00:50 CST 2013
     */
    int insertSelective(FsQdfPaymentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PAYMENT_INFO
     *
     * @mbggenerated Tue May 21 16:00:50 CST 2013
     */
    List<FsQdfPaymentInfo> selectByExample(FsQdfPaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PAYMENT_INFO
     *
     * @mbggenerated Tue May 21 16:00:50 CST 2013
     */
    int updateByExampleSelective(@Param("record") FsQdfPaymentInfo record, @Param("example") FsQdfPaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PAYMENT_INFO
     *
     * @mbggenerated Tue May 21 16:00:50 CST 2013
     */
    int updateByExample(@Param("record") FsQdfPaymentInfo record, @Param("example") FsQdfPaymentInfoExample example);
}