package fis.repository.qdf.dao;

import fis.repository.qdf.model.FsQdfPendingVchInfo;
import fis.repository.qdf.model.FsQdfPendingVchInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FsQdfPendingVchInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Sun May 19 21:55:18 CST 2013
     */
    int countByExample(FsQdfPendingVchInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Sun May 19 21:55:18 CST 2013
     */
    int deleteByExample(FsQdfPendingVchInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Sun May 19 21:55:18 CST 2013
     */
    int insert(FsQdfPendingVchInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Sun May 19 21:55:18 CST 2013
     */
    int insertSelective(FsQdfPendingVchInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Sun May 19 21:55:18 CST 2013
     */
    List<FsQdfPendingVchInfo> selectByExample(FsQdfPendingVchInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Sun May 19 21:55:18 CST 2013
     */
    int updateByExampleSelective(@Param("record") FsQdfPendingVchInfo record, @Param("example") FsQdfPendingVchInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_QDF_PENDING_VCH_INFO
     *
     * @mbggenerated Sun May 19 21:55:18 CST 2013
     */
    int updateByExample(@Param("record") FsQdfPendingVchInfo record, @Param("example") FsQdfPendingVchInfoExample example);
}