package fis.repository.pay.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PayAccreditvoucherExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.PAY_ACCREDITVOUCHER
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.PAY_ACCREDITVOUCHER
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.PAY_ACCREDITVOUCHER
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.PAY_ACCREDITVOUCHER
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public PayAccreditvoucherExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.PAY_ACCREDITVOUCHER
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.PAY_ACCREDITVOUCHER
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.PAY_ACCREDITVOUCHER
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.PAY_ACCREDITVOUCHER
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.PAY_ACCREDITVOUCHER
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.PAY_ACCREDITVOUCHER
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.PAY_ACCREDITVOUCHER
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.PAY_ACCREDITVOUCHER
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.PAY_ACCREDITVOUCHER
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.PAY_ACCREDITVOUCHER
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.PAY_ACCREDITVOUCHER
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andBillcodeIsNull() {
            addCriterion("BILLCODE is null");
            return (Criteria) this;
        }

        public Criteria andBillcodeIsNotNull() {
            addCriterion("BILLCODE is not null");
            return (Criteria) this;
        }

        public Criteria andBillcodeEqualTo(String value) {
            addCriterion("BILLCODE =", value, "billcode");
            return (Criteria) this;
        }

        public Criteria andBillcodeNotEqualTo(String value) {
            addCriterion("BILLCODE <>", value, "billcode");
            return (Criteria) this;
        }

        public Criteria andBillcodeGreaterThan(String value) {
            addCriterion("BILLCODE >", value, "billcode");
            return (Criteria) this;
        }

        public Criteria andBillcodeGreaterThanOrEqualTo(String value) {
            addCriterion("BILLCODE >=", value, "billcode");
            return (Criteria) this;
        }

        public Criteria andBillcodeLessThan(String value) {
            addCriterion("BILLCODE <", value, "billcode");
            return (Criteria) this;
        }

        public Criteria andBillcodeLessThanOrEqualTo(String value) {
            addCriterion("BILLCODE <=", value, "billcode");
            return (Criteria) this;
        }

        public Criteria andBillcodeLike(String value) {
            addCriterion("BILLCODE like", value, "billcode");
            return (Criteria) this;
        }

        public Criteria andBillcodeNotLike(String value) {
            addCriterion("BILLCODE not like", value, "billcode");
            return (Criteria) this;
        }

        public Criteria andBillcodeIn(List<String> values) {
            addCriterion("BILLCODE in", values, "billcode");
            return (Criteria) this;
        }

        public Criteria andBillcodeNotIn(List<String> values) {
            addCriterion("BILLCODE not in", values, "billcode");
            return (Criteria) this;
        }

        public Criteria andBillcodeBetween(String value1, String value2) {
            addCriterion("BILLCODE between", value1, value2, "billcode");
            return (Criteria) this;
        }

        public Criteria andBillcodeNotBetween(String value1, String value2) {
            addCriterion("BILLCODE not between", value1, value2, "billcode");
            return (Criteria) this;
        }

        public Criteria andBankIsNull() {
            addCriterion("BANK is null");
            return (Criteria) this;
        }

        public Criteria andBankIsNotNull() {
            addCriterion("BANK is not null");
            return (Criteria) this;
        }

        public Criteria andBankEqualTo(String value) {
            addCriterion("BANK =", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankNotEqualTo(String value) {
            addCriterion("BANK <>", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankGreaterThan(String value) {
            addCriterion("BANK >", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankGreaterThanOrEqualTo(String value) {
            addCriterion("BANK >=", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankLessThan(String value) {
            addCriterion("BANK <", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankLessThanOrEqualTo(String value) {
            addCriterion("BANK <=", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankLike(String value) {
            addCriterion("BANK like", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankNotLike(String value) {
            addCriterion("BANK not like", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankIn(List<String> values) {
            addCriterion("BANK in", values, "bank");
            return (Criteria) this;
        }

        public Criteria andBankNotIn(List<String> values) {
            addCriterion("BANK not in", values, "bank");
            return (Criteria) this;
        }

        public Criteria andBankBetween(String value1, String value2) {
            addCriterion("BANK between", value1, value2, "bank");
            return (Criteria) this;
        }

        public Criteria andBankNotBetween(String value1, String value2) {
            addCriterion("BANK not between", value1, value2, "bank");
            return (Criteria) this;
        }

        public Criteria andDepartmentcodeIsNull() {
            addCriterion("DEPARTMENTCODE is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentcodeIsNotNull() {
            addCriterion("DEPARTMENTCODE is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentcodeEqualTo(String value) {
            addCriterion("DEPARTMENTCODE =", value, "departmentcode");
            return (Criteria) this;
        }

        public Criteria andDepartmentcodeNotEqualTo(String value) {
            addCriterion("DEPARTMENTCODE <>", value, "departmentcode");
            return (Criteria) this;
        }

        public Criteria andDepartmentcodeGreaterThan(String value) {
            addCriterion("DEPARTMENTCODE >", value, "departmentcode");
            return (Criteria) this;
        }

        public Criteria andDepartmentcodeGreaterThanOrEqualTo(String value) {
            addCriterion("DEPARTMENTCODE >=", value, "departmentcode");
            return (Criteria) this;
        }

        public Criteria andDepartmentcodeLessThan(String value) {
            addCriterion("DEPARTMENTCODE <", value, "departmentcode");
            return (Criteria) this;
        }

        public Criteria andDepartmentcodeLessThanOrEqualTo(String value) {
            addCriterion("DEPARTMENTCODE <=", value, "departmentcode");
            return (Criteria) this;
        }

        public Criteria andDepartmentcodeLike(String value) {
            addCriterion("DEPARTMENTCODE like", value, "departmentcode");
            return (Criteria) this;
        }

        public Criteria andDepartmentcodeNotLike(String value) {
            addCriterion("DEPARTMENTCODE not like", value, "departmentcode");
            return (Criteria) this;
        }

        public Criteria andDepartmentcodeIn(List<String> values) {
            addCriterion("DEPARTMENTCODE in", values, "departmentcode");
            return (Criteria) this;
        }

        public Criteria andDepartmentcodeNotIn(List<String> values) {
            addCriterion("DEPARTMENTCODE not in", values, "departmentcode");
            return (Criteria) this;
        }

        public Criteria andDepartmentcodeBetween(String value1, String value2) {
            addCriterion("DEPARTMENTCODE between", value1, value2, "departmentcode");
            return (Criteria) this;
        }

        public Criteria andDepartmentcodeNotBetween(String value1, String value2) {
            addCriterion("DEPARTMENTCODE not between", value1, value2, "departmentcode");
            return (Criteria) this;
        }

        public Criteria andDepartmentnameIsNull() {
            addCriterion("DEPARTMENTNAME is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentnameIsNotNull() {
            addCriterion("DEPARTMENTNAME is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentnameEqualTo(String value) {
            addCriterion("DEPARTMENTNAME =", value, "departmentname");
            return (Criteria) this;
        }

        public Criteria andDepartmentnameNotEqualTo(String value) {
            addCriterion("DEPARTMENTNAME <>", value, "departmentname");
            return (Criteria) this;
        }

        public Criteria andDepartmentnameGreaterThan(String value) {
            addCriterion("DEPARTMENTNAME >", value, "departmentname");
            return (Criteria) this;
        }

        public Criteria andDepartmentnameGreaterThanOrEqualTo(String value) {
            addCriterion("DEPARTMENTNAME >=", value, "departmentname");
            return (Criteria) this;
        }

        public Criteria andDepartmentnameLessThan(String value) {
            addCriterion("DEPARTMENTNAME <", value, "departmentname");
            return (Criteria) this;
        }

        public Criteria andDepartmentnameLessThanOrEqualTo(String value) {
            addCriterion("DEPARTMENTNAME <=", value, "departmentname");
            return (Criteria) this;
        }

        public Criteria andDepartmentnameLike(String value) {
            addCriterion("DEPARTMENTNAME like", value, "departmentname");
            return (Criteria) this;
        }

        public Criteria andDepartmentnameNotLike(String value) {
            addCriterion("DEPARTMENTNAME not like", value, "departmentname");
            return (Criteria) this;
        }

        public Criteria andDepartmentnameIn(List<String> values) {
            addCriterion("DEPARTMENTNAME in", values, "departmentname");
            return (Criteria) this;
        }

        public Criteria andDepartmentnameNotIn(List<String> values) {
            addCriterion("DEPARTMENTNAME not in", values, "departmentname");
            return (Criteria) this;
        }

        public Criteria andDepartmentnameBetween(String value1, String value2) {
            addCriterion("DEPARTMENTNAME between", value1, value2, "departmentname");
            return (Criteria) this;
        }

        public Criteria andDepartmentnameNotBetween(String value1, String value2) {
            addCriterion("DEPARTMENTNAME not between", value1, value2, "departmentname");
            return (Criteria) this;
        }

        public Criteria andBdgagencycodeIsNull() {
            addCriterion("BDGAGENCYCODE is null");
            return (Criteria) this;
        }

        public Criteria andBdgagencycodeIsNotNull() {
            addCriterion("BDGAGENCYCODE is not null");
            return (Criteria) this;
        }

        public Criteria andBdgagencycodeEqualTo(String value) {
            addCriterion("BDGAGENCYCODE =", value, "bdgagencycode");
            return (Criteria) this;
        }

        public Criteria andBdgagencycodeNotEqualTo(String value) {
            addCriterion("BDGAGENCYCODE <>", value, "bdgagencycode");
            return (Criteria) this;
        }

        public Criteria andBdgagencycodeGreaterThan(String value) {
            addCriterion("BDGAGENCYCODE >", value, "bdgagencycode");
            return (Criteria) this;
        }

        public Criteria andBdgagencycodeGreaterThanOrEqualTo(String value) {
            addCriterion("BDGAGENCYCODE >=", value, "bdgagencycode");
            return (Criteria) this;
        }

        public Criteria andBdgagencycodeLessThan(String value) {
            addCriterion("BDGAGENCYCODE <", value, "bdgagencycode");
            return (Criteria) this;
        }

        public Criteria andBdgagencycodeLessThanOrEqualTo(String value) {
            addCriterion("BDGAGENCYCODE <=", value, "bdgagencycode");
            return (Criteria) this;
        }

        public Criteria andBdgagencycodeLike(String value) {
            addCriterion("BDGAGENCYCODE like", value, "bdgagencycode");
            return (Criteria) this;
        }

        public Criteria andBdgagencycodeNotLike(String value) {
            addCriterion("BDGAGENCYCODE not like", value, "bdgagencycode");
            return (Criteria) this;
        }

        public Criteria andBdgagencycodeIn(List<String> values) {
            addCriterion("BDGAGENCYCODE in", values, "bdgagencycode");
            return (Criteria) this;
        }

        public Criteria andBdgagencycodeNotIn(List<String> values) {
            addCriterion("BDGAGENCYCODE not in", values, "bdgagencycode");
            return (Criteria) this;
        }

        public Criteria andBdgagencycodeBetween(String value1, String value2) {
            addCriterion("BDGAGENCYCODE between", value1, value2, "bdgagencycode");
            return (Criteria) this;
        }

        public Criteria andBdgagencycodeNotBetween(String value1, String value2) {
            addCriterion("BDGAGENCYCODE not between", value1, value2, "bdgagencycode");
            return (Criteria) this;
        }

        public Criteria andBdgagencynameIsNull() {
            addCriterion("BDGAGENCYNAME is null");
            return (Criteria) this;
        }

        public Criteria andBdgagencynameIsNotNull() {
            addCriterion("BDGAGENCYNAME is not null");
            return (Criteria) this;
        }

        public Criteria andBdgagencynameEqualTo(String value) {
            addCriterion("BDGAGENCYNAME =", value, "bdgagencyname");
            return (Criteria) this;
        }

        public Criteria andBdgagencynameNotEqualTo(String value) {
            addCriterion("BDGAGENCYNAME <>", value, "bdgagencyname");
            return (Criteria) this;
        }

        public Criteria andBdgagencynameGreaterThan(String value) {
            addCriterion("BDGAGENCYNAME >", value, "bdgagencyname");
            return (Criteria) this;
        }

        public Criteria andBdgagencynameGreaterThanOrEqualTo(String value) {
            addCriterion("BDGAGENCYNAME >=", value, "bdgagencyname");
            return (Criteria) this;
        }

        public Criteria andBdgagencynameLessThan(String value) {
            addCriterion("BDGAGENCYNAME <", value, "bdgagencyname");
            return (Criteria) this;
        }

        public Criteria andBdgagencynameLessThanOrEqualTo(String value) {
            addCriterion("BDGAGENCYNAME <=", value, "bdgagencyname");
            return (Criteria) this;
        }

        public Criteria andBdgagencynameLike(String value) {
            addCriterion("BDGAGENCYNAME like", value, "bdgagencyname");
            return (Criteria) this;
        }

        public Criteria andBdgagencynameNotLike(String value) {
            addCriterion("BDGAGENCYNAME not like", value, "bdgagencyname");
            return (Criteria) this;
        }

        public Criteria andBdgagencynameIn(List<String> values) {
            addCriterion("BDGAGENCYNAME in", values, "bdgagencyname");
            return (Criteria) this;
        }

        public Criteria andBdgagencynameNotIn(List<String> values) {
            addCriterion("BDGAGENCYNAME not in", values, "bdgagencyname");
            return (Criteria) this;
        }

        public Criteria andBdgagencynameBetween(String value1, String value2) {
            addCriterion("BDGAGENCYNAME between", value1, value2, "bdgagencyname");
            return (Criteria) this;
        }

        public Criteria andBdgagencynameNotBetween(String value1, String value2) {
            addCriterion("BDGAGENCYNAME not between", value1, value2, "bdgagencyname");
            return (Criteria) this;
        }

        public Criteria andMonthIsNull() {
            addCriterion("MONTH is null");
            return (Criteria) this;
        }

        public Criteria andMonthIsNotNull() {
            addCriterion("MONTH is not null");
            return (Criteria) this;
        }

        public Criteria andMonthEqualTo(Short value) {
            addCriterion("MONTH =", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotEqualTo(Short value) {
            addCriterion("MONTH <>", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthGreaterThan(Short value) {
            addCriterion("MONTH >", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthGreaterThanOrEqualTo(Short value) {
            addCriterion("MONTH >=", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthLessThan(Short value) {
            addCriterion("MONTH <", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthLessThanOrEqualTo(Short value) {
            addCriterion("MONTH <=", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthIn(List<Short> values) {
            addCriterion("MONTH in", values, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotIn(List<Short> values) {
            addCriterion("MONTH not in", values, "month");
            return (Criteria) this;
        }

        public Criteria andMonthBetween(Short value1, Short value2) {
            addCriterion("MONTH between", value1, value2, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotBetween(Short value1, Short value2) {
            addCriterion("MONTH not between", value1, value2, "month");
            return (Criteria) this;
        }

        public Criteria andFunccodeIsNull() {
            addCriterion("FUNCCODE is null");
            return (Criteria) this;
        }

        public Criteria andFunccodeIsNotNull() {
            addCriterion("FUNCCODE is not null");
            return (Criteria) this;
        }

        public Criteria andFunccodeEqualTo(String value) {
            addCriterion("FUNCCODE =", value, "funccode");
            return (Criteria) this;
        }

        public Criteria andFunccodeNotEqualTo(String value) {
            addCriterion("FUNCCODE <>", value, "funccode");
            return (Criteria) this;
        }

        public Criteria andFunccodeGreaterThan(String value) {
            addCriterion("FUNCCODE >", value, "funccode");
            return (Criteria) this;
        }

        public Criteria andFunccodeGreaterThanOrEqualTo(String value) {
            addCriterion("FUNCCODE >=", value, "funccode");
            return (Criteria) this;
        }

        public Criteria andFunccodeLessThan(String value) {
            addCriterion("FUNCCODE <", value, "funccode");
            return (Criteria) this;
        }

        public Criteria andFunccodeLessThanOrEqualTo(String value) {
            addCriterion("FUNCCODE <=", value, "funccode");
            return (Criteria) this;
        }

        public Criteria andFunccodeLike(String value) {
            addCriterion("FUNCCODE like", value, "funccode");
            return (Criteria) this;
        }

        public Criteria andFunccodeNotLike(String value) {
            addCriterion("FUNCCODE not like", value, "funccode");
            return (Criteria) this;
        }

        public Criteria andFunccodeIn(List<String> values) {
            addCriterion("FUNCCODE in", values, "funccode");
            return (Criteria) this;
        }

        public Criteria andFunccodeNotIn(List<String> values) {
            addCriterion("FUNCCODE not in", values, "funccode");
            return (Criteria) this;
        }

        public Criteria andFunccodeBetween(String value1, String value2) {
            addCriterion("FUNCCODE between", value1, value2, "funccode");
            return (Criteria) this;
        }

        public Criteria andFunccodeNotBetween(String value1, String value2) {
            addCriterion("FUNCCODE not between", value1, value2, "funccode");
            return (Criteria) this;
        }

        public Criteria andFuncnameIsNull() {
            addCriterion("FUNCNAME is null");
            return (Criteria) this;
        }

        public Criteria andFuncnameIsNotNull() {
            addCriterion("FUNCNAME is not null");
            return (Criteria) this;
        }

        public Criteria andFuncnameEqualTo(String value) {
            addCriterion("FUNCNAME =", value, "funcname");
            return (Criteria) this;
        }

        public Criteria andFuncnameNotEqualTo(String value) {
            addCriterion("FUNCNAME <>", value, "funcname");
            return (Criteria) this;
        }

        public Criteria andFuncnameGreaterThan(String value) {
            addCriterion("FUNCNAME >", value, "funcname");
            return (Criteria) this;
        }

        public Criteria andFuncnameGreaterThanOrEqualTo(String value) {
            addCriterion("FUNCNAME >=", value, "funcname");
            return (Criteria) this;
        }

        public Criteria andFuncnameLessThan(String value) {
            addCriterion("FUNCNAME <", value, "funcname");
            return (Criteria) this;
        }

        public Criteria andFuncnameLessThanOrEqualTo(String value) {
            addCriterion("FUNCNAME <=", value, "funcname");
            return (Criteria) this;
        }

        public Criteria andFuncnameLike(String value) {
            addCriterion("FUNCNAME like", value, "funcname");
            return (Criteria) this;
        }

        public Criteria andFuncnameNotLike(String value) {
            addCriterion("FUNCNAME not like", value, "funcname");
            return (Criteria) this;
        }

        public Criteria andFuncnameIn(List<String> values) {
            addCriterion("FUNCNAME in", values, "funcname");
            return (Criteria) this;
        }

        public Criteria andFuncnameNotIn(List<String> values) {
            addCriterion("FUNCNAME not in", values, "funcname");
            return (Criteria) this;
        }

        public Criteria andFuncnameBetween(String value1, String value2) {
            addCriterion("FUNCNAME between", value1, value2, "funcname");
            return (Criteria) this;
        }

        public Criteria andFuncnameNotBetween(String value1, String value2) {
            addCriterion("FUNCNAME not between", value1, value2, "funcname");
            return (Criteria) this;
        }

        public Criteria andProgramcodeIsNull() {
            addCriterion("PROGRAMCODE is null");
            return (Criteria) this;
        }

        public Criteria andProgramcodeIsNotNull() {
            addCriterion("PROGRAMCODE is not null");
            return (Criteria) this;
        }

        public Criteria andProgramcodeEqualTo(String value) {
            addCriterion("PROGRAMCODE =", value, "programcode");
            return (Criteria) this;
        }

        public Criteria andProgramcodeNotEqualTo(String value) {
            addCriterion("PROGRAMCODE <>", value, "programcode");
            return (Criteria) this;
        }

        public Criteria andProgramcodeGreaterThan(String value) {
            addCriterion("PROGRAMCODE >", value, "programcode");
            return (Criteria) this;
        }

        public Criteria andProgramcodeGreaterThanOrEqualTo(String value) {
            addCriterion("PROGRAMCODE >=", value, "programcode");
            return (Criteria) this;
        }

        public Criteria andProgramcodeLessThan(String value) {
            addCriterion("PROGRAMCODE <", value, "programcode");
            return (Criteria) this;
        }

        public Criteria andProgramcodeLessThanOrEqualTo(String value) {
            addCriterion("PROGRAMCODE <=", value, "programcode");
            return (Criteria) this;
        }

        public Criteria andProgramcodeLike(String value) {
            addCriterion("PROGRAMCODE like", value, "programcode");
            return (Criteria) this;
        }

        public Criteria andProgramcodeNotLike(String value) {
            addCriterion("PROGRAMCODE not like", value, "programcode");
            return (Criteria) this;
        }

        public Criteria andProgramcodeIn(List<String> values) {
            addCriterion("PROGRAMCODE in", values, "programcode");
            return (Criteria) this;
        }

        public Criteria andProgramcodeNotIn(List<String> values) {
            addCriterion("PROGRAMCODE not in", values, "programcode");
            return (Criteria) this;
        }

        public Criteria andProgramcodeBetween(String value1, String value2) {
            addCriterion("PROGRAMCODE between", value1, value2, "programcode");
            return (Criteria) this;
        }

        public Criteria andProgramcodeNotBetween(String value1, String value2) {
            addCriterion("PROGRAMCODE not between", value1, value2, "programcode");
            return (Criteria) this;
        }

        public Criteria andProgramnameIsNull() {
            addCriterion("PROGRAMNAME is null");
            return (Criteria) this;
        }

        public Criteria andProgramnameIsNotNull() {
            addCriterion("PROGRAMNAME is not null");
            return (Criteria) this;
        }

        public Criteria andProgramnameEqualTo(String value) {
            addCriterion("PROGRAMNAME =", value, "programname");
            return (Criteria) this;
        }

        public Criteria andProgramnameNotEqualTo(String value) {
            addCriterion("PROGRAMNAME <>", value, "programname");
            return (Criteria) this;
        }

        public Criteria andProgramnameGreaterThan(String value) {
            addCriterion("PROGRAMNAME >", value, "programname");
            return (Criteria) this;
        }

        public Criteria andProgramnameGreaterThanOrEqualTo(String value) {
            addCriterion("PROGRAMNAME >=", value, "programname");
            return (Criteria) this;
        }

        public Criteria andProgramnameLessThan(String value) {
            addCriterion("PROGRAMNAME <", value, "programname");
            return (Criteria) this;
        }

        public Criteria andProgramnameLessThanOrEqualTo(String value) {
            addCriterion("PROGRAMNAME <=", value, "programname");
            return (Criteria) this;
        }

        public Criteria andProgramnameLike(String value) {
            addCriterion("PROGRAMNAME like", value, "programname");
            return (Criteria) this;
        }

        public Criteria andProgramnameNotLike(String value) {
            addCriterion("PROGRAMNAME not like", value, "programname");
            return (Criteria) this;
        }

        public Criteria andProgramnameIn(List<String> values) {
            addCriterion("PROGRAMNAME in", values, "programname");
            return (Criteria) this;
        }

        public Criteria andProgramnameNotIn(List<String> values) {
            addCriterion("PROGRAMNAME not in", values, "programname");
            return (Criteria) this;
        }

        public Criteria andProgramnameBetween(String value1, String value2) {
            addCriterion("PROGRAMNAME between", value1, value2, "programname");
            return (Criteria) this;
        }

        public Criteria andProgramnameNotBetween(String value1, String value2) {
            addCriterion("PROGRAMNAME not between", value1, value2, "programname");
            return (Criteria) this;
        }

        public Criteria andPaybankaccountIsNull() {
            addCriterion("PAYBANKACCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andPaybankaccountIsNotNull() {
            addCriterion("PAYBANKACCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andPaybankaccountEqualTo(String value) {
            addCriterion("PAYBANKACCOUNT =", value, "paybankaccount");
            return (Criteria) this;
        }

        public Criteria andPaybankaccountNotEqualTo(String value) {
            addCriterion("PAYBANKACCOUNT <>", value, "paybankaccount");
            return (Criteria) this;
        }

        public Criteria andPaybankaccountGreaterThan(String value) {
            addCriterion("PAYBANKACCOUNT >", value, "paybankaccount");
            return (Criteria) this;
        }

        public Criteria andPaybankaccountGreaterThanOrEqualTo(String value) {
            addCriterion("PAYBANKACCOUNT >=", value, "paybankaccount");
            return (Criteria) this;
        }

        public Criteria andPaybankaccountLessThan(String value) {
            addCriterion("PAYBANKACCOUNT <", value, "paybankaccount");
            return (Criteria) this;
        }

        public Criteria andPaybankaccountLessThanOrEqualTo(String value) {
            addCriterion("PAYBANKACCOUNT <=", value, "paybankaccount");
            return (Criteria) this;
        }

        public Criteria andPaybankaccountLike(String value) {
            addCriterion("PAYBANKACCOUNT like", value, "paybankaccount");
            return (Criteria) this;
        }

        public Criteria andPaybankaccountNotLike(String value) {
            addCriterion("PAYBANKACCOUNT not like", value, "paybankaccount");
            return (Criteria) this;
        }

        public Criteria andPaybankaccountIn(List<String> values) {
            addCriterion("PAYBANKACCOUNT in", values, "paybankaccount");
            return (Criteria) this;
        }

        public Criteria andPaybankaccountNotIn(List<String> values) {
            addCriterion("PAYBANKACCOUNT not in", values, "paybankaccount");
            return (Criteria) this;
        }

        public Criteria andPaybankaccountBetween(String value1, String value2) {
            addCriterion("PAYBANKACCOUNT between", value1, value2, "paybankaccount");
            return (Criteria) this;
        }

        public Criteria andPaybankaccountNotBetween(String value1, String value2) {
            addCriterion("PAYBANKACCOUNT not between", value1, value2, "paybankaccount");
            return (Criteria) this;
        }

        public Criteria andAmtIsNull() {
            addCriterion("AMT is null");
            return (Criteria) this;
        }

        public Criteria andAmtIsNotNull() {
            addCriterion("AMT is not null");
            return (Criteria) this;
        }

        public Criteria andAmtEqualTo(BigDecimal value) {
            addCriterion("AMT =", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotEqualTo(BigDecimal value) {
            addCriterion("AMT <>", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtGreaterThan(BigDecimal value) {
            addCriterion("AMT >", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AMT >=", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtLessThan(BigDecimal value) {
            addCriterion("AMT <", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AMT <=", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtIn(List<BigDecimal> values) {
            addCriterion("AMT in", values, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotIn(List<BigDecimal> values) {
            addCriterion("AMT not in", values, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AMT between", value1, value2, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AMT not between", value1, value2, "amt");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("CREATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("CREATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(String value) {
            addCriterion("CREATEDATE =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(String value) {
            addCriterion("CREATEDATE <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(String value) {
            addCriterion("CREATEDATE >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEDATE >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(String value) {
            addCriterion("CREATEDATE <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(String value) {
            addCriterion("CREATEDATE <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLike(String value) {
            addCriterion("CREATEDATE like", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotLike(String value) {
            addCriterion("CREATEDATE not like", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<String> values) {
            addCriterion("CREATEDATE in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<String> values) {
            addCriterion("CREATEDATE not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(String value1, String value2) {
            addCriterion("CREATEDATE between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(String value1, String value2) {
            addCriterion("CREATEDATE not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andFundtypeIsNull() {
            addCriterion("FUNDTYPE is null");
            return (Criteria) this;
        }

        public Criteria andFundtypeIsNotNull() {
            addCriterion("FUNDTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andFundtypeEqualTo(String value) {
            addCriterion("FUNDTYPE =", value, "fundtype");
            return (Criteria) this;
        }

        public Criteria andFundtypeNotEqualTo(String value) {
            addCriterion("FUNDTYPE <>", value, "fundtype");
            return (Criteria) this;
        }

        public Criteria andFundtypeGreaterThan(String value) {
            addCriterion("FUNDTYPE >", value, "fundtype");
            return (Criteria) this;
        }

        public Criteria andFundtypeGreaterThanOrEqualTo(String value) {
            addCriterion("FUNDTYPE >=", value, "fundtype");
            return (Criteria) this;
        }

        public Criteria andFundtypeLessThan(String value) {
            addCriterion("FUNDTYPE <", value, "fundtype");
            return (Criteria) this;
        }

        public Criteria andFundtypeLessThanOrEqualTo(String value) {
            addCriterion("FUNDTYPE <=", value, "fundtype");
            return (Criteria) this;
        }

        public Criteria andFundtypeLike(String value) {
            addCriterion("FUNDTYPE like", value, "fundtype");
            return (Criteria) this;
        }

        public Criteria andFundtypeNotLike(String value) {
            addCriterion("FUNDTYPE not like", value, "fundtype");
            return (Criteria) this;
        }

        public Criteria andFundtypeIn(List<String> values) {
            addCriterion("FUNDTYPE in", values, "fundtype");
            return (Criteria) this;
        }

        public Criteria andFundtypeNotIn(List<String> values) {
            addCriterion("FUNDTYPE not in", values, "fundtype");
            return (Criteria) this;
        }

        public Criteria andFundtypeBetween(String value1, String value2) {
            addCriterion("FUNDTYPE between", value1, value2, "fundtype");
            return (Criteria) this;
        }

        public Criteria andFundtypeNotBetween(String value1, String value2) {
            addCriterion("FUNDTYPE not between", value1, value2, "fundtype");
            return (Criteria) this;
        }

        public Criteria andIndsourceIsNull() {
            addCriterion("INDSOURCE is null");
            return (Criteria) this;
        }

        public Criteria andIndsourceIsNotNull() {
            addCriterion("INDSOURCE is not null");
            return (Criteria) this;
        }

        public Criteria andIndsourceEqualTo(String value) {
            addCriterion("INDSOURCE =", value, "indsource");
            return (Criteria) this;
        }

        public Criteria andIndsourceNotEqualTo(String value) {
            addCriterion("INDSOURCE <>", value, "indsource");
            return (Criteria) this;
        }

        public Criteria andIndsourceGreaterThan(String value) {
            addCriterion("INDSOURCE >", value, "indsource");
            return (Criteria) this;
        }

        public Criteria andIndsourceGreaterThanOrEqualTo(String value) {
            addCriterion("INDSOURCE >=", value, "indsource");
            return (Criteria) this;
        }

        public Criteria andIndsourceLessThan(String value) {
            addCriterion("INDSOURCE <", value, "indsource");
            return (Criteria) this;
        }

        public Criteria andIndsourceLessThanOrEqualTo(String value) {
            addCriterion("INDSOURCE <=", value, "indsource");
            return (Criteria) this;
        }

        public Criteria andIndsourceLike(String value) {
            addCriterion("INDSOURCE like", value, "indsource");
            return (Criteria) this;
        }

        public Criteria andIndsourceNotLike(String value) {
            addCriterion("INDSOURCE not like", value, "indsource");
            return (Criteria) this;
        }

        public Criteria andIndsourceIn(List<String> values) {
            addCriterion("INDSOURCE in", values, "indsource");
            return (Criteria) this;
        }

        public Criteria andIndsourceNotIn(List<String> values) {
            addCriterion("INDSOURCE not in", values, "indsource");
            return (Criteria) this;
        }

        public Criteria andIndsourceBetween(String value1, String value2) {
            addCriterion("INDSOURCE between", value1, value2, "indsource");
            return (Criteria) this;
        }

        public Criteria andIndsourceNotBetween(String value1, String value2) {
            addCriterion("INDSOURCE not between", value1, value2, "indsource");
            return (Criteria) this;
        }

        public Criteria andGuidIsNull() {
            addCriterion("GUID is null");
            return (Criteria) this;
        }

        public Criteria andGuidIsNotNull() {
            addCriterion("GUID is not null");
            return (Criteria) this;
        }

        public Criteria andGuidEqualTo(String value) {
            addCriterion("GUID =", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotEqualTo(String value) {
            addCriterion("GUID <>", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidGreaterThan(String value) {
            addCriterion("GUID >", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidGreaterThanOrEqualTo(String value) {
            addCriterion("GUID >=", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLessThan(String value) {
            addCriterion("GUID <", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLessThanOrEqualTo(String value) {
            addCriterion("GUID <=", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLike(String value) {
            addCriterion("GUID like", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotLike(String value) {
            addCriterion("GUID not like", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidIn(List<String> values) {
            addCriterion("GUID in", values, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotIn(List<String> values) {
            addCriterion("GUID not in", values, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidBetween(String value1, String value2) {
            addCriterion("GUID between", value1, value2, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotBetween(String value1, String value2) {
            addCriterion("GUID not between", value1, value2, "guid");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("CREATED_BY is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("CREATED_BY is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("CREATED_BY =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("CREATED_BY <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("CREATED_BY >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("CREATED_BY >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("CREATED_BY <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("CREATED_BY <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("CREATED_BY like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("CREATED_BY not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("CREATED_BY in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("CREATED_BY not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("CREATED_BY between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("CREATED_BY not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedDtIsNull() {
            addCriterion("CREATED_DT is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDtIsNotNull() {
            addCriterion("CREATED_DT is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDtEqualTo(Date value) {
            addCriterion("CREATED_DT =", value, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtNotEqualTo(Date value) {
            addCriterion("CREATED_DT <>", value, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtGreaterThan(Date value) {
            addCriterion("CREATED_DT >", value, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATED_DT >=", value, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtLessThan(Date value) {
            addCriterion("CREATED_DT <", value, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtLessThanOrEqualTo(Date value) {
            addCriterion("CREATED_DT <=", value, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtIn(List<Date> values) {
            addCriterion("CREATED_DT in", values, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtNotIn(List<Date> values) {
            addCriterion("CREATED_DT not in", values, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtBetween(Date value1, Date value2) {
            addCriterion("CREATED_DT between", value1, value2, "createdDt");
            return (Criteria) this;
        }

        public Criteria andCreatedDtNotBetween(Date value1, Date value2) {
            addCriterion("CREATED_DT not between", value1, value2, "createdDt");
            return (Criteria) this;
        }

        public Criteria andLastUpdByIsNull() {
            addCriterion("LAST_UPD_BY is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdByIsNotNull() {
            addCriterion("LAST_UPD_BY is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdByEqualTo(String value) {
            addCriterion("LAST_UPD_BY =", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByNotEqualTo(String value) {
            addCriterion("LAST_UPD_BY <>", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByGreaterThan(String value) {
            addCriterion("LAST_UPD_BY >", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_UPD_BY >=", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByLessThan(String value) {
            addCriterion("LAST_UPD_BY <", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByLessThanOrEqualTo(String value) {
            addCriterion("LAST_UPD_BY <=", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByLike(String value) {
            addCriterion("LAST_UPD_BY like", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByNotLike(String value) {
            addCriterion("LAST_UPD_BY not like", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByIn(List<String> values) {
            addCriterion("LAST_UPD_BY in", values, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByNotIn(List<String> values) {
            addCriterion("LAST_UPD_BY not in", values, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByBetween(String value1, String value2) {
            addCriterion("LAST_UPD_BY between", value1, value2, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByNotBetween(String value1, String value2) {
            addCriterion("LAST_UPD_BY not between", value1, value2, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateIsNull() {
            addCriterion("LAST_UPD_DATE is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateIsNotNull() {
            addCriterion("LAST_UPD_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateEqualTo(Date value) {
            addCriterion("LAST_UPD_DATE =", value, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateNotEqualTo(Date value) {
            addCriterion("LAST_UPD_DATE <>", value, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateGreaterThan(Date value) {
            addCriterion("LAST_UPD_DATE >", value, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_UPD_DATE >=", value, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateLessThan(Date value) {
            addCriterion("LAST_UPD_DATE <", value, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateLessThanOrEqualTo(Date value) {
            addCriterion("LAST_UPD_DATE <=", value, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateIn(List<Date> values) {
            addCriterion("LAST_UPD_DATE in", values, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateNotIn(List<Date> values) {
            addCriterion("LAST_UPD_DATE not in", values, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateBetween(Date value1, Date value2) {
            addCriterion("LAST_UPD_DATE between", value1, value2, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateNotBetween(Date value1, Date value2) {
            addCriterion("LAST_UPD_DATE not between", value1, value2, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andAreacodeIsNull() {
            addCriterion("AREACODE is null");
            return (Criteria) this;
        }

        public Criteria andAreacodeIsNotNull() {
            addCriterion("AREACODE is not null");
            return (Criteria) this;
        }

        public Criteria andAreacodeEqualTo(String value) {
            addCriterion("AREACODE =", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeNotEqualTo(String value) {
            addCriterion("AREACODE <>", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeGreaterThan(String value) {
            addCriterion("AREACODE >", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeGreaterThanOrEqualTo(String value) {
            addCriterion("AREACODE >=", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeLessThan(String value) {
            addCriterion("AREACODE <", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeLessThanOrEqualTo(String value) {
            addCriterion("AREACODE <=", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeLike(String value) {
            addCriterion("AREACODE like", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeNotLike(String value) {
            addCriterion("AREACODE not like", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeIn(List<String> values) {
            addCriterion("AREACODE in", values, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeNotIn(List<String> values) {
            addCriterion("AREACODE not in", values, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeBetween(String value1, String value2) {
            addCriterion("AREACODE between", value1, value2, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeNotBetween(String value1, String value2) {
            addCriterion("AREACODE not between", value1, value2, "areacode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.PAY_ACCREDITVOUCHER
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 18 10:56:33 CST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.PAY_ACCREDITVOUCHER
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}