package fis.repository.pay.model;

import java.math.BigDecimal;
import java.util.Date;

public class PayAccreditvoucher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_ACCREDITVOUCHER.PKID
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_ACCREDITVOUCHER.BILLCODE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String billcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_ACCREDITVOUCHER.BANK
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String bank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_ACCREDITVOUCHER.DEPARTMENTCODE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String departmentcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_ACCREDITVOUCHER.DEPARTMENTNAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String departmentname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_ACCREDITVOUCHER.BDGAGENCYCODE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String bdgagencycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_ACCREDITVOUCHER.BDGAGENCYNAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String bdgagencyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_ACCREDITVOUCHER.MONTH
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private Short month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_ACCREDITVOUCHER.FUNCCODE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String funccode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_ACCREDITVOUCHER.FUNCNAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String funcname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_ACCREDITVOUCHER.PROGRAMCODE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String programcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_ACCREDITVOUCHER.PROGRAMNAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String programname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_ACCREDITVOUCHER.PAYBANKACCOUNT
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String paybankaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_ACCREDITVOUCHER.AMT
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private BigDecimal amt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_ACCREDITVOUCHER.CREATEDATE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_ACCREDITVOUCHER.FUNDTYPE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String fundtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_ACCREDITVOUCHER.INDSOURCE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String indsource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_ACCREDITVOUCHER.GUID
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_ACCREDITVOUCHER.CREATED_BY
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_ACCREDITVOUCHER.CREATED_DT
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private Date createdDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_ACCREDITVOUCHER.LAST_UPD_BY
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String lastUpdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_ACCREDITVOUCHER.LAST_UPD_DATE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private Date lastUpdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_ACCREDITVOUCHER.AREACODE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String areacode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_ACCREDITVOUCHER.PKID
     *
     * @return the value of FIS.PAY_ACCREDITVOUCHER.PKID
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_ACCREDITVOUCHER.PKID
     *
     * @param pkid the value for FIS.PAY_ACCREDITVOUCHER.PKID
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_ACCREDITVOUCHER.BILLCODE
     *
     * @return the value of FIS.PAY_ACCREDITVOUCHER.BILLCODE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getBillcode() {
        return billcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_ACCREDITVOUCHER.BILLCODE
     *
     * @param billcode the value for FIS.PAY_ACCREDITVOUCHER.BILLCODE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setBillcode(String billcode) {
        this.billcode = billcode == null ? null : billcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_ACCREDITVOUCHER.BANK
     *
     * @return the value of FIS.PAY_ACCREDITVOUCHER.BANK
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_ACCREDITVOUCHER.BANK
     *
     * @param bank the value for FIS.PAY_ACCREDITVOUCHER.BANK
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_ACCREDITVOUCHER.DEPARTMENTCODE
     *
     * @return the value of FIS.PAY_ACCREDITVOUCHER.DEPARTMENTCODE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getDepartmentcode() {
        return departmentcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_ACCREDITVOUCHER.DEPARTMENTCODE
     *
     * @param departmentcode the value for FIS.PAY_ACCREDITVOUCHER.DEPARTMENTCODE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setDepartmentcode(String departmentcode) {
        this.departmentcode = departmentcode == null ? null : departmentcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_ACCREDITVOUCHER.DEPARTMENTNAME
     *
     * @return the value of FIS.PAY_ACCREDITVOUCHER.DEPARTMENTNAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getDepartmentname() {
        return departmentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_ACCREDITVOUCHER.DEPARTMENTNAME
     *
     * @param departmentname the value for FIS.PAY_ACCREDITVOUCHER.DEPARTMENTNAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setDepartmentname(String departmentname) {
        this.departmentname = departmentname == null ? null : departmentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_ACCREDITVOUCHER.BDGAGENCYCODE
     *
     * @return the value of FIS.PAY_ACCREDITVOUCHER.BDGAGENCYCODE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getBdgagencycode() {
        return bdgagencycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_ACCREDITVOUCHER.BDGAGENCYCODE
     *
     * @param bdgagencycode the value for FIS.PAY_ACCREDITVOUCHER.BDGAGENCYCODE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setBdgagencycode(String bdgagencycode) {
        this.bdgagencycode = bdgagencycode == null ? null : bdgagencycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_ACCREDITVOUCHER.BDGAGENCYNAME
     *
     * @return the value of FIS.PAY_ACCREDITVOUCHER.BDGAGENCYNAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getBdgagencyname() {
        return bdgagencyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_ACCREDITVOUCHER.BDGAGENCYNAME
     *
     * @param bdgagencyname the value for FIS.PAY_ACCREDITVOUCHER.BDGAGENCYNAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setBdgagencyname(String bdgagencyname) {
        this.bdgagencyname = bdgagencyname == null ? null : bdgagencyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_ACCREDITVOUCHER.MONTH
     *
     * @return the value of FIS.PAY_ACCREDITVOUCHER.MONTH
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public Short getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_ACCREDITVOUCHER.MONTH
     *
     * @param month the value for FIS.PAY_ACCREDITVOUCHER.MONTH
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setMonth(Short month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_ACCREDITVOUCHER.FUNCCODE
     *
     * @return the value of FIS.PAY_ACCREDITVOUCHER.FUNCCODE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getFunccode() {
        return funccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_ACCREDITVOUCHER.FUNCCODE
     *
     * @param funccode the value for FIS.PAY_ACCREDITVOUCHER.FUNCCODE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setFunccode(String funccode) {
        this.funccode = funccode == null ? null : funccode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_ACCREDITVOUCHER.FUNCNAME
     *
     * @return the value of FIS.PAY_ACCREDITVOUCHER.FUNCNAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getFuncname() {
        return funcname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_ACCREDITVOUCHER.FUNCNAME
     *
     * @param funcname the value for FIS.PAY_ACCREDITVOUCHER.FUNCNAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setFuncname(String funcname) {
        this.funcname = funcname == null ? null : funcname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_ACCREDITVOUCHER.PROGRAMCODE
     *
     * @return the value of FIS.PAY_ACCREDITVOUCHER.PROGRAMCODE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getProgramcode() {
        return programcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_ACCREDITVOUCHER.PROGRAMCODE
     *
     * @param programcode the value for FIS.PAY_ACCREDITVOUCHER.PROGRAMCODE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setProgramcode(String programcode) {
        this.programcode = programcode == null ? null : programcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_ACCREDITVOUCHER.PROGRAMNAME
     *
     * @return the value of FIS.PAY_ACCREDITVOUCHER.PROGRAMNAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getProgramname() {
        return programname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_ACCREDITVOUCHER.PROGRAMNAME
     *
     * @param programname the value for FIS.PAY_ACCREDITVOUCHER.PROGRAMNAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setProgramname(String programname) {
        this.programname = programname == null ? null : programname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_ACCREDITVOUCHER.PAYBANKACCOUNT
     *
     * @return the value of FIS.PAY_ACCREDITVOUCHER.PAYBANKACCOUNT
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getPaybankaccount() {
        return paybankaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_ACCREDITVOUCHER.PAYBANKACCOUNT
     *
     * @param paybankaccount the value for FIS.PAY_ACCREDITVOUCHER.PAYBANKACCOUNT
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setPaybankaccount(String paybankaccount) {
        this.paybankaccount = paybankaccount == null ? null : paybankaccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_ACCREDITVOUCHER.AMT
     *
     * @return the value of FIS.PAY_ACCREDITVOUCHER.AMT
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public BigDecimal getAmt() {
        return amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_ACCREDITVOUCHER.AMT
     *
     * @param amt the value for FIS.PAY_ACCREDITVOUCHER.AMT
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setAmt(BigDecimal amt) {
        this.amt = amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_ACCREDITVOUCHER.CREATEDATE
     *
     * @return the value of FIS.PAY_ACCREDITVOUCHER.CREATEDATE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_ACCREDITVOUCHER.CREATEDATE
     *
     * @param createdate the value for FIS.PAY_ACCREDITVOUCHER.CREATEDATE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate == null ? null : createdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_ACCREDITVOUCHER.FUNDTYPE
     *
     * @return the value of FIS.PAY_ACCREDITVOUCHER.FUNDTYPE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getFundtype() {
        return fundtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_ACCREDITVOUCHER.FUNDTYPE
     *
     * @param fundtype the value for FIS.PAY_ACCREDITVOUCHER.FUNDTYPE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setFundtype(String fundtype) {
        this.fundtype = fundtype == null ? null : fundtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_ACCREDITVOUCHER.INDSOURCE
     *
     * @return the value of FIS.PAY_ACCREDITVOUCHER.INDSOURCE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getIndsource() {
        return indsource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_ACCREDITVOUCHER.INDSOURCE
     *
     * @param indsource the value for FIS.PAY_ACCREDITVOUCHER.INDSOURCE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setIndsource(String indsource) {
        this.indsource = indsource == null ? null : indsource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_ACCREDITVOUCHER.GUID
     *
     * @return the value of FIS.PAY_ACCREDITVOUCHER.GUID
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_ACCREDITVOUCHER.GUID
     *
     * @param guid the value for FIS.PAY_ACCREDITVOUCHER.GUID
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_ACCREDITVOUCHER.CREATED_BY
     *
     * @return the value of FIS.PAY_ACCREDITVOUCHER.CREATED_BY
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_ACCREDITVOUCHER.CREATED_BY
     *
     * @param createdBy the value for FIS.PAY_ACCREDITVOUCHER.CREATED_BY
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_ACCREDITVOUCHER.CREATED_DT
     *
     * @return the value of FIS.PAY_ACCREDITVOUCHER.CREATED_DT
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public Date getCreatedDt() {
        return createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_ACCREDITVOUCHER.CREATED_DT
     *
     * @param createdDt the value for FIS.PAY_ACCREDITVOUCHER.CREATED_DT
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setCreatedDt(Date createdDt) {
        this.createdDt = createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_ACCREDITVOUCHER.LAST_UPD_BY
     *
     * @return the value of FIS.PAY_ACCREDITVOUCHER.LAST_UPD_BY
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getLastUpdBy() {
        return lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_ACCREDITVOUCHER.LAST_UPD_BY
     *
     * @param lastUpdBy the value for FIS.PAY_ACCREDITVOUCHER.LAST_UPD_BY
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setLastUpdBy(String lastUpdBy) {
        this.lastUpdBy = lastUpdBy == null ? null : lastUpdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_ACCREDITVOUCHER.LAST_UPD_DATE
     *
     * @return the value of FIS.PAY_ACCREDITVOUCHER.LAST_UPD_DATE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public Date getLastUpdDate() {
        return lastUpdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_ACCREDITVOUCHER.LAST_UPD_DATE
     *
     * @param lastUpdDate the value for FIS.PAY_ACCREDITVOUCHER.LAST_UPD_DATE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setLastUpdDate(Date lastUpdDate) {
        this.lastUpdDate = lastUpdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_ACCREDITVOUCHER.AREACODE
     *
     * @return the value of FIS.PAY_ACCREDITVOUCHER.AREACODE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_ACCREDITVOUCHER.AREACODE
     *
     * @param areacode the value for FIS.PAY_ACCREDITVOUCHER.AREACODE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode == null ? null : areacode.trim();
    }
}