package fis.repository.pay.model;

import java.math.BigDecimal;
import java.util.Date;

public class PayPayvoucher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.PKID
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.PRINTID
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String printid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.CREATEDATE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.CLEARBANK
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String clearbank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.PAYBANKACCOUNT
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String paybankaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.PAY
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String pay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.PAYBANK
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String paybank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.PAYEEBANKACCOUNT
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String payeebankaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.PAYEE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String payee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.PAYEEBANK
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String payeebank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.AMT
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private BigDecimal amt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.BDGAGENCY
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String bdgagency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.DEPARTMENT
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.BDGMANAGEDIVISION
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String bdgmanagedivision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.EXPFUNC
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String expfunc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.EXPECO
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String expeco;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.PROGRAM
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String program;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.PAYTYPE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String paytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.PAYKIND
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String paykind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.SETTLEMODE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String settlemode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.REMARK
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.GUID
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.VOUCHERTYPE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String vouchertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.CENTRALCODE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String centralcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.INDSOURCE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String indsource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.FUNDTYPE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String fundtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.RESOLVECODE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String resolvecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.PROCESSFLAG
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String processflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.CREATED_BY
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.CREATED_DT
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private Date createdDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.LAST_UPD_BY
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String lastUpdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.LAST_UPD_DATE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private Date lastUpdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.BDGAGENCYNAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String bdgagencyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.DEPARTMENTNAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String departmentname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.BDGMANAGEDIVNAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String bdgmanagedivname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.EXPFUNCNAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String expfuncname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.EXPECONAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String expeconame;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.PROGRAMNAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String programname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.PAYTYPENAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String paytypename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.PAYKINDNAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String paykindname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.SETTLEMODENAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String settlemodename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.PAY_PAYVOUCHER.AREACODE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    private String areacode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.PKID
     *
     * @return the value of FIS.PAY_PAYVOUCHER.PKID
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.PKID
     *
     * @param pkid the value for FIS.PAY_PAYVOUCHER.PKID
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.PRINTID
     *
     * @return the value of FIS.PAY_PAYVOUCHER.PRINTID
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getPrintid() {
        return printid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.PRINTID
     *
     * @param printid the value for FIS.PAY_PAYVOUCHER.PRINTID
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setPrintid(String printid) {
        this.printid = printid == null ? null : printid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.CREATEDATE
     *
     * @return the value of FIS.PAY_PAYVOUCHER.CREATEDATE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.CREATEDATE
     *
     * @param createdate the value for FIS.PAY_PAYVOUCHER.CREATEDATE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate == null ? null : createdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.CLEARBANK
     *
     * @return the value of FIS.PAY_PAYVOUCHER.CLEARBANK
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getClearbank() {
        return clearbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.CLEARBANK
     *
     * @param clearbank the value for FIS.PAY_PAYVOUCHER.CLEARBANK
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setClearbank(String clearbank) {
        this.clearbank = clearbank == null ? null : clearbank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.PAYBANKACCOUNT
     *
     * @return the value of FIS.PAY_PAYVOUCHER.PAYBANKACCOUNT
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getPaybankaccount() {
        return paybankaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.PAYBANKACCOUNT
     *
     * @param paybankaccount the value for FIS.PAY_PAYVOUCHER.PAYBANKACCOUNT
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setPaybankaccount(String paybankaccount) {
        this.paybankaccount = paybankaccount == null ? null : paybankaccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.PAY
     *
     * @return the value of FIS.PAY_PAYVOUCHER.PAY
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getPay() {
        return pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.PAY
     *
     * @param pay the value for FIS.PAY_PAYVOUCHER.PAY
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setPay(String pay) {
        this.pay = pay == null ? null : pay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.PAYBANK
     *
     * @return the value of FIS.PAY_PAYVOUCHER.PAYBANK
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getPaybank() {
        return paybank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.PAYBANK
     *
     * @param paybank the value for FIS.PAY_PAYVOUCHER.PAYBANK
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setPaybank(String paybank) {
        this.paybank = paybank == null ? null : paybank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.PAYEEBANKACCOUNT
     *
     * @return the value of FIS.PAY_PAYVOUCHER.PAYEEBANKACCOUNT
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getPayeebankaccount() {
        return payeebankaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.PAYEEBANKACCOUNT
     *
     * @param payeebankaccount the value for FIS.PAY_PAYVOUCHER.PAYEEBANKACCOUNT
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setPayeebankaccount(String payeebankaccount) {
        this.payeebankaccount = payeebankaccount == null ? null : payeebankaccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.PAYEE
     *
     * @return the value of FIS.PAY_PAYVOUCHER.PAYEE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getPayee() {
        return payee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.PAYEE
     *
     * @param payee the value for FIS.PAY_PAYVOUCHER.PAYEE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setPayee(String payee) {
        this.payee = payee == null ? null : payee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.PAYEEBANK
     *
     * @return the value of FIS.PAY_PAYVOUCHER.PAYEEBANK
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getPayeebank() {
        return payeebank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.PAYEEBANK
     *
     * @param payeebank the value for FIS.PAY_PAYVOUCHER.PAYEEBANK
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setPayeebank(String payeebank) {
        this.payeebank = payeebank == null ? null : payeebank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.AMT
     *
     * @return the value of FIS.PAY_PAYVOUCHER.AMT
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public BigDecimal getAmt() {
        return amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.AMT
     *
     * @param amt the value for FIS.PAY_PAYVOUCHER.AMT
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setAmt(BigDecimal amt) {
        this.amt = amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.BDGAGENCY
     *
     * @return the value of FIS.PAY_PAYVOUCHER.BDGAGENCY
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getBdgagency() {
        return bdgagency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.BDGAGENCY
     *
     * @param bdgagency the value for FIS.PAY_PAYVOUCHER.BDGAGENCY
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setBdgagency(String bdgagency) {
        this.bdgagency = bdgagency == null ? null : bdgagency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.DEPARTMENT
     *
     * @return the value of FIS.PAY_PAYVOUCHER.DEPARTMENT
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.DEPARTMENT
     *
     * @param department the value for FIS.PAY_PAYVOUCHER.DEPARTMENT
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.BDGMANAGEDIVISION
     *
     * @return the value of FIS.PAY_PAYVOUCHER.BDGMANAGEDIVISION
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getBdgmanagedivision() {
        return bdgmanagedivision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.BDGMANAGEDIVISION
     *
     * @param bdgmanagedivision the value for FIS.PAY_PAYVOUCHER.BDGMANAGEDIVISION
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setBdgmanagedivision(String bdgmanagedivision) {
        this.bdgmanagedivision = bdgmanagedivision == null ? null : bdgmanagedivision.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.EXPFUNC
     *
     * @return the value of FIS.PAY_PAYVOUCHER.EXPFUNC
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getExpfunc() {
        return expfunc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.EXPFUNC
     *
     * @param expfunc the value for FIS.PAY_PAYVOUCHER.EXPFUNC
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setExpfunc(String expfunc) {
        this.expfunc = expfunc == null ? null : expfunc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.EXPECO
     *
     * @return the value of FIS.PAY_PAYVOUCHER.EXPECO
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getExpeco() {
        return expeco;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.EXPECO
     *
     * @param expeco the value for FIS.PAY_PAYVOUCHER.EXPECO
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setExpeco(String expeco) {
        this.expeco = expeco == null ? null : expeco.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.PROGRAM
     *
     * @return the value of FIS.PAY_PAYVOUCHER.PROGRAM
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getProgram() {
        return program;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.PROGRAM
     *
     * @param program the value for FIS.PAY_PAYVOUCHER.PROGRAM
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setProgram(String program) {
        this.program = program == null ? null : program.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.PAYTYPE
     *
     * @return the value of FIS.PAY_PAYVOUCHER.PAYTYPE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.PAYTYPE
     *
     * @param paytype the value for FIS.PAY_PAYVOUCHER.PAYTYPE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setPaytype(String paytype) {
        this.paytype = paytype == null ? null : paytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.PAYKIND
     *
     * @return the value of FIS.PAY_PAYVOUCHER.PAYKIND
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getPaykind() {
        return paykind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.PAYKIND
     *
     * @param paykind the value for FIS.PAY_PAYVOUCHER.PAYKIND
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setPaykind(String paykind) {
        this.paykind = paykind == null ? null : paykind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.SETTLEMODE
     *
     * @return the value of FIS.PAY_PAYVOUCHER.SETTLEMODE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getSettlemode() {
        return settlemode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.SETTLEMODE
     *
     * @param settlemode the value for FIS.PAY_PAYVOUCHER.SETTLEMODE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setSettlemode(String settlemode) {
        this.settlemode = settlemode == null ? null : settlemode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.REMARK
     *
     * @return the value of FIS.PAY_PAYVOUCHER.REMARK
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.REMARK
     *
     * @param remark the value for FIS.PAY_PAYVOUCHER.REMARK
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.GUID
     *
     * @return the value of FIS.PAY_PAYVOUCHER.GUID
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.GUID
     *
     * @param guid the value for FIS.PAY_PAYVOUCHER.GUID
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.VOUCHERTYPE
     *
     * @return the value of FIS.PAY_PAYVOUCHER.VOUCHERTYPE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getVouchertype() {
        return vouchertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.VOUCHERTYPE
     *
     * @param vouchertype the value for FIS.PAY_PAYVOUCHER.VOUCHERTYPE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setVouchertype(String vouchertype) {
        this.vouchertype = vouchertype == null ? null : vouchertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.CENTRALCODE
     *
     * @return the value of FIS.PAY_PAYVOUCHER.CENTRALCODE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getCentralcode() {
        return centralcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.CENTRALCODE
     *
     * @param centralcode the value for FIS.PAY_PAYVOUCHER.CENTRALCODE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setCentralcode(String centralcode) {
        this.centralcode = centralcode == null ? null : centralcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.INDSOURCE
     *
     * @return the value of FIS.PAY_PAYVOUCHER.INDSOURCE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getIndsource() {
        return indsource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.INDSOURCE
     *
     * @param indsource the value for FIS.PAY_PAYVOUCHER.INDSOURCE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setIndsource(String indsource) {
        this.indsource = indsource == null ? null : indsource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.FUNDTYPE
     *
     * @return the value of FIS.PAY_PAYVOUCHER.FUNDTYPE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getFundtype() {
        return fundtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.FUNDTYPE
     *
     * @param fundtype the value for FIS.PAY_PAYVOUCHER.FUNDTYPE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setFundtype(String fundtype) {
        this.fundtype = fundtype == null ? null : fundtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.RESOLVECODE
     *
     * @return the value of FIS.PAY_PAYVOUCHER.RESOLVECODE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getResolvecode() {
        return resolvecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.RESOLVECODE
     *
     * @param resolvecode the value for FIS.PAY_PAYVOUCHER.RESOLVECODE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setResolvecode(String resolvecode) {
        this.resolvecode = resolvecode == null ? null : resolvecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.PROCESSFLAG
     *
     * @return the value of FIS.PAY_PAYVOUCHER.PROCESSFLAG
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getProcessflag() {
        return processflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.PROCESSFLAG
     *
     * @param processflag the value for FIS.PAY_PAYVOUCHER.PROCESSFLAG
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setProcessflag(String processflag) {
        this.processflag = processflag == null ? null : processflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.CREATED_BY
     *
     * @return the value of FIS.PAY_PAYVOUCHER.CREATED_BY
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.CREATED_BY
     *
     * @param createdBy the value for FIS.PAY_PAYVOUCHER.CREATED_BY
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.CREATED_DT
     *
     * @return the value of FIS.PAY_PAYVOUCHER.CREATED_DT
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public Date getCreatedDt() {
        return createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.CREATED_DT
     *
     * @param createdDt the value for FIS.PAY_PAYVOUCHER.CREATED_DT
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setCreatedDt(Date createdDt) {
        this.createdDt = createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.LAST_UPD_BY
     *
     * @return the value of FIS.PAY_PAYVOUCHER.LAST_UPD_BY
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getLastUpdBy() {
        return lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.LAST_UPD_BY
     *
     * @param lastUpdBy the value for FIS.PAY_PAYVOUCHER.LAST_UPD_BY
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setLastUpdBy(String lastUpdBy) {
        this.lastUpdBy = lastUpdBy == null ? null : lastUpdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.LAST_UPD_DATE
     *
     * @return the value of FIS.PAY_PAYVOUCHER.LAST_UPD_DATE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public Date getLastUpdDate() {
        return lastUpdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.LAST_UPD_DATE
     *
     * @param lastUpdDate the value for FIS.PAY_PAYVOUCHER.LAST_UPD_DATE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setLastUpdDate(Date lastUpdDate) {
        this.lastUpdDate = lastUpdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.BDGAGENCYNAME
     *
     * @return the value of FIS.PAY_PAYVOUCHER.BDGAGENCYNAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getBdgagencyname() {
        return bdgagencyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.BDGAGENCYNAME
     *
     * @param bdgagencyname the value for FIS.PAY_PAYVOUCHER.BDGAGENCYNAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setBdgagencyname(String bdgagencyname) {
        this.bdgagencyname = bdgagencyname == null ? null : bdgagencyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.DEPARTMENTNAME
     *
     * @return the value of FIS.PAY_PAYVOUCHER.DEPARTMENTNAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getDepartmentname() {
        return departmentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.DEPARTMENTNAME
     *
     * @param departmentname the value for FIS.PAY_PAYVOUCHER.DEPARTMENTNAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setDepartmentname(String departmentname) {
        this.departmentname = departmentname == null ? null : departmentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.BDGMANAGEDIVNAME
     *
     * @return the value of FIS.PAY_PAYVOUCHER.BDGMANAGEDIVNAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getBdgmanagedivname() {
        return bdgmanagedivname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.BDGMANAGEDIVNAME
     *
     * @param bdgmanagedivname the value for FIS.PAY_PAYVOUCHER.BDGMANAGEDIVNAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setBdgmanagedivname(String bdgmanagedivname) {
        this.bdgmanagedivname = bdgmanagedivname == null ? null : bdgmanagedivname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.EXPFUNCNAME
     *
     * @return the value of FIS.PAY_PAYVOUCHER.EXPFUNCNAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getExpfuncname() {
        return expfuncname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.EXPFUNCNAME
     *
     * @param expfuncname the value for FIS.PAY_PAYVOUCHER.EXPFUNCNAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setExpfuncname(String expfuncname) {
        this.expfuncname = expfuncname == null ? null : expfuncname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.EXPECONAME
     *
     * @return the value of FIS.PAY_PAYVOUCHER.EXPECONAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getExpeconame() {
        return expeconame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.EXPECONAME
     *
     * @param expeconame the value for FIS.PAY_PAYVOUCHER.EXPECONAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setExpeconame(String expeconame) {
        this.expeconame = expeconame == null ? null : expeconame.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.PROGRAMNAME
     *
     * @return the value of FIS.PAY_PAYVOUCHER.PROGRAMNAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getProgramname() {
        return programname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.PROGRAMNAME
     *
     * @param programname the value for FIS.PAY_PAYVOUCHER.PROGRAMNAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setProgramname(String programname) {
        this.programname = programname == null ? null : programname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.PAYTYPENAME
     *
     * @return the value of FIS.PAY_PAYVOUCHER.PAYTYPENAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getPaytypename() {
        return paytypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.PAYTYPENAME
     *
     * @param paytypename the value for FIS.PAY_PAYVOUCHER.PAYTYPENAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setPaytypename(String paytypename) {
        this.paytypename = paytypename == null ? null : paytypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.PAYKINDNAME
     *
     * @return the value of FIS.PAY_PAYVOUCHER.PAYKINDNAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getPaykindname() {
        return paykindname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.PAYKINDNAME
     *
     * @param paykindname the value for FIS.PAY_PAYVOUCHER.PAYKINDNAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setPaykindname(String paykindname) {
        this.paykindname = paykindname == null ? null : paykindname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.SETTLEMODENAME
     *
     * @return the value of FIS.PAY_PAYVOUCHER.SETTLEMODENAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getSettlemodename() {
        return settlemodename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.SETTLEMODENAME
     *
     * @param settlemodename the value for FIS.PAY_PAYVOUCHER.SETTLEMODENAME
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setSettlemodename(String settlemodename) {
        this.settlemodename = settlemodename == null ? null : settlemodename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.PAY_PAYVOUCHER.AREACODE
     *
     * @return the value of FIS.PAY_PAYVOUCHER.AREACODE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.PAY_PAYVOUCHER.AREACODE
     *
     * @param areacode the value for FIS.PAY_PAYVOUCHER.AREACODE
     *
     * @mbggenerated Wed Jan 18 10:56:33 CST 2012
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode == null ? null : areacode.trim();
    }
}